// Code generated by ent, DO NOT EDIT.

package teamdefinition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/plexusone/agentplexus/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldID, id))
}

// RepoName applies equality check predicate on the "repo_name" field. It's identical to RepoNameEQ.
func RepoName(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldRepoName, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldName, v))
}

// SourceRef applies equality check predicate on the "source_ref" field. It's identical to SourceRefEQ.
func SourceRef(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldSourceRef, v))
}

// RegistryXrn applies equality check predicate on the "registry_xrn" field. It's identical to RegistryXrnEQ.
func RegistryXrn(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldRegistryXrn, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldVersion, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldDescription, v))
}

// Orchestrator applies equality check predicate on the "orchestrator" field. It's identical to OrchestratorEQ.
func Orchestrator(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldOrchestrator, v))
}

// SourcePath applies equality check predicate on the "source_path" field. It's identical to SourcePathEQ.
func SourcePath(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldSourcePath, v))
}

// ContentHash applies equality check predicate on the "content_hash" field. It's identical to ContentHashEQ.
func ContentHash(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldContentHash, v))
}

// FirstSeenAt applies equality check predicate on the "first_seen_at" field. It's identical to FirstSeenAtEQ.
func FirstSeenAt(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldFirstSeenAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// RepoNameEQ applies the EQ predicate on the "repo_name" field.
func RepoNameEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldRepoName, v))
}

// RepoNameNEQ applies the NEQ predicate on the "repo_name" field.
func RepoNameNEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldRepoName, v))
}

// RepoNameIn applies the In predicate on the "repo_name" field.
func RepoNameIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldRepoName, vs...))
}

// RepoNameNotIn applies the NotIn predicate on the "repo_name" field.
func RepoNameNotIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldRepoName, vs...))
}

// RepoNameGT applies the GT predicate on the "repo_name" field.
func RepoNameGT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldRepoName, v))
}

// RepoNameGTE applies the GTE predicate on the "repo_name" field.
func RepoNameGTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldRepoName, v))
}

// RepoNameLT applies the LT predicate on the "repo_name" field.
func RepoNameLT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldRepoName, v))
}

// RepoNameLTE applies the LTE predicate on the "repo_name" field.
func RepoNameLTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldRepoName, v))
}

// RepoNameContains applies the Contains predicate on the "repo_name" field.
func RepoNameContains(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContains(FieldRepoName, v))
}

// RepoNameHasPrefix applies the HasPrefix predicate on the "repo_name" field.
func RepoNameHasPrefix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasPrefix(FieldRepoName, v))
}

// RepoNameHasSuffix applies the HasSuffix predicate on the "repo_name" field.
func RepoNameHasSuffix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasSuffix(FieldRepoName, v))
}

// RepoNameEqualFold applies the EqualFold predicate on the "repo_name" field.
func RepoNameEqualFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEqualFold(FieldRepoName, v))
}

// RepoNameContainsFold applies the ContainsFold predicate on the "repo_name" field.
func RepoNameContainsFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContainsFold(FieldRepoName, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContainsFold(FieldName, v))
}

// SourceRefEQ applies the EQ predicate on the "source_ref" field.
func SourceRefEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldSourceRef, v))
}

// SourceRefNEQ applies the NEQ predicate on the "source_ref" field.
func SourceRefNEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldSourceRef, v))
}

// SourceRefIn applies the In predicate on the "source_ref" field.
func SourceRefIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldSourceRef, vs...))
}

// SourceRefNotIn applies the NotIn predicate on the "source_ref" field.
func SourceRefNotIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldSourceRef, vs...))
}

// SourceRefGT applies the GT predicate on the "source_ref" field.
func SourceRefGT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldSourceRef, v))
}

// SourceRefGTE applies the GTE predicate on the "source_ref" field.
func SourceRefGTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldSourceRef, v))
}

// SourceRefLT applies the LT predicate on the "source_ref" field.
func SourceRefLT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldSourceRef, v))
}

// SourceRefLTE applies the LTE predicate on the "source_ref" field.
func SourceRefLTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldSourceRef, v))
}

// SourceRefContains applies the Contains predicate on the "source_ref" field.
func SourceRefContains(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContains(FieldSourceRef, v))
}

// SourceRefHasPrefix applies the HasPrefix predicate on the "source_ref" field.
func SourceRefHasPrefix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasPrefix(FieldSourceRef, v))
}

// SourceRefHasSuffix applies the HasSuffix predicate on the "source_ref" field.
func SourceRefHasSuffix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasSuffix(FieldSourceRef, v))
}

// SourceRefIsNil applies the IsNil predicate on the "source_ref" field.
func SourceRefIsNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIsNull(FieldSourceRef))
}

// SourceRefNotNil applies the NotNil predicate on the "source_ref" field.
func SourceRefNotNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotNull(FieldSourceRef))
}

// SourceRefEqualFold applies the EqualFold predicate on the "source_ref" field.
func SourceRefEqualFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEqualFold(FieldSourceRef, v))
}

// SourceRefContainsFold applies the ContainsFold predicate on the "source_ref" field.
func SourceRefContainsFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContainsFold(FieldSourceRef, v))
}

// RegistryXrnEQ applies the EQ predicate on the "registry_xrn" field.
func RegistryXrnEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldRegistryXrn, v))
}

// RegistryXrnNEQ applies the NEQ predicate on the "registry_xrn" field.
func RegistryXrnNEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldRegistryXrn, v))
}

// RegistryXrnIn applies the In predicate on the "registry_xrn" field.
func RegistryXrnIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldRegistryXrn, vs...))
}

// RegistryXrnNotIn applies the NotIn predicate on the "registry_xrn" field.
func RegistryXrnNotIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldRegistryXrn, vs...))
}

// RegistryXrnGT applies the GT predicate on the "registry_xrn" field.
func RegistryXrnGT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldRegistryXrn, v))
}

// RegistryXrnGTE applies the GTE predicate on the "registry_xrn" field.
func RegistryXrnGTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldRegistryXrn, v))
}

// RegistryXrnLT applies the LT predicate on the "registry_xrn" field.
func RegistryXrnLT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldRegistryXrn, v))
}

// RegistryXrnLTE applies the LTE predicate on the "registry_xrn" field.
func RegistryXrnLTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldRegistryXrn, v))
}

// RegistryXrnContains applies the Contains predicate on the "registry_xrn" field.
func RegistryXrnContains(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContains(FieldRegistryXrn, v))
}

// RegistryXrnHasPrefix applies the HasPrefix predicate on the "registry_xrn" field.
func RegistryXrnHasPrefix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasPrefix(FieldRegistryXrn, v))
}

// RegistryXrnHasSuffix applies the HasSuffix predicate on the "registry_xrn" field.
func RegistryXrnHasSuffix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasSuffix(FieldRegistryXrn, v))
}

// RegistryXrnIsNil applies the IsNil predicate on the "registry_xrn" field.
func RegistryXrnIsNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIsNull(FieldRegistryXrn))
}

// RegistryXrnNotNil applies the NotNil predicate on the "registry_xrn" field.
func RegistryXrnNotNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotNull(FieldRegistryXrn))
}

// RegistryXrnEqualFold applies the EqualFold predicate on the "registry_xrn" field.
func RegistryXrnEqualFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEqualFold(FieldRegistryXrn, v))
}

// RegistryXrnContainsFold applies the ContainsFold predicate on the "registry_xrn" field.
func RegistryXrnContainsFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContainsFold(FieldRegistryXrn, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionIsNil applies the IsNil predicate on the "version" field.
func VersionIsNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIsNull(FieldVersion))
}

// VersionNotNil applies the NotNil predicate on the "version" field.
func VersionNotNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotNull(FieldVersion))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContainsFold(FieldVersion, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContainsFold(FieldDescription, v))
}

// OrchestratorEQ applies the EQ predicate on the "orchestrator" field.
func OrchestratorEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldOrchestrator, v))
}

// OrchestratorNEQ applies the NEQ predicate on the "orchestrator" field.
func OrchestratorNEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldOrchestrator, v))
}

// OrchestratorIn applies the In predicate on the "orchestrator" field.
func OrchestratorIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldOrchestrator, vs...))
}

// OrchestratorNotIn applies the NotIn predicate on the "orchestrator" field.
func OrchestratorNotIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldOrchestrator, vs...))
}

// OrchestratorGT applies the GT predicate on the "orchestrator" field.
func OrchestratorGT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldOrchestrator, v))
}

// OrchestratorGTE applies the GTE predicate on the "orchestrator" field.
func OrchestratorGTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldOrchestrator, v))
}

// OrchestratorLT applies the LT predicate on the "orchestrator" field.
func OrchestratorLT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldOrchestrator, v))
}

// OrchestratorLTE applies the LTE predicate on the "orchestrator" field.
func OrchestratorLTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldOrchestrator, v))
}

// OrchestratorContains applies the Contains predicate on the "orchestrator" field.
func OrchestratorContains(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContains(FieldOrchestrator, v))
}

// OrchestratorHasPrefix applies the HasPrefix predicate on the "orchestrator" field.
func OrchestratorHasPrefix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasPrefix(FieldOrchestrator, v))
}

// OrchestratorHasSuffix applies the HasSuffix predicate on the "orchestrator" field.
func OrchestratorHasSuffix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasSuffix(FieldOrchestrator, v))
}

// OrchestratorIsNil applies the IsNil predicate on the "orchestrator" field.
func OrchestratorIsNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIsNull(FieldOrchestrator))
}

// OrchestratorNotNil applies the NotNil predicate on the "orchestrator" field.
func OrchestratorNotNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotNull(FieldOrchestrator))
}

// OrchestratorEqualFold applies the EqualFold predicate on the "orchestrator" field.
func OrchestratorEqualFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEqualFold(FieldOrchestrator, v))
}

// OrchestratorContainsFold applies the ContainsFold predicate on the "orchestrator" field.
func OrchestratorContainsFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContainsFold(FieldOrchestrator, v))
}

// AgentNamesIsNil applies the IsNil predicate on the "agent_names" field.
func AgentNamesIsNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIsNull(FieldAgentNames))
}

// AgentNamesNotNil applies the NotNil predicate on the "agent_names" field.
func AgentNamesNotNil() predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotNull(FieldAgentNames))
}

// SourcePathEQ applies the EQ predicate on the "source_path" field.
func SourcePathEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldSourcePath, v))
}

// SourcePathNEQ applies the NEQ predicate on the "source_path" field.
func SourcePathNEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldSourcePath, v))
}

// SourcePathIn applies the In predicate on the "source_path" field.
func SourcePathIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldSourcePath, vs...))
}

// SourcePathNotIn applies the NotIn predicate on the "source_path" field.
func SourcePathNotIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldSourcePath, vs...))
}

// SourcePathGT applies the GT predicate on the "source_path" field.
func SourcePathGT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldSourcePath, v))
}

// SourcePathGTE applies the GTE predicate on the "source_path" field.
func SourcePathGTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldSourcePath, v))
}

// SourcePathLT applies the LT predicate on the "source_path" field.
func SourcePathLT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldSourcePath, v))
}

// SourcePathLTE applies the LTE predicate on the "source_path" field.
func SourcePathLTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldSourcePath, v))
}

// SourcePathContains applies the Contains predicate on the "source_path" field.
func SourcePathContains(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContains(FieldSourcePath, v))
}

// SourcePathHasPrefix applies the HasPrefix predicate on the "source_path" field.
func SourcePathHasPrefix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasPrefix(FieldSourcePath, v))
}

// SourcePathHasSuffix applies the HasSuffix predicate on the "source_path" field.
func SourcePathHasSuffix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasSuffix(FieldSourcePath, v))
}

// SourcePathEqualFold applies the EqualFold predicate on the "source_path" field.
func SourcePathEqualFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEqualFold(FieldSourcePath, v))
}

// SourcePathContainsFold applies the ContainsFold predicate on the "source_path" field.
func SourcePathContainsFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContainsFold(FieldSourcePath, v))
}

// ContentHashEQ applies the EQ predicate on the "content_hash" field.
func ContentHashEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldContentHash, v))
}

// ContentHashNEQ applies the NEQ predicate on the "content_hash" field.
func ContentHashNEQ(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldContentHash, v))
}

// ContentHashIn applies the In predicate on the "content_hash" field.
func ContentHashIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldContentHash, vs...))
}

// ContentHashNotIn applies the NotIn predicate on the "content_hash" field.
func ContentHashNotIn(vs ...string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldContentHash, vs...))
}

// ContentHashGT applies the GT predicate on the "content_hash" field.
func ContentHashGT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldContentHash, v))
}

// ContentHashGTE applies the GTE predicate on the "content_hash" field.
func ContentHashGTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldContentHash, v))
}

// ContentHashLT applies the LT predicate on the "content_hash" field.
func ContentHashLT(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldContentHash, v))
}

// ContentHashLTE applies the LTE predicate on the "content_hash" field.
func ContentHashLTE(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldContentHash, v))
}

// ContentHashContains applies the Contains predicate on the "content_hash" field.
func ContentHashContains(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContains(FieldContentHash, v))
}

// ContentHashHasPrefix applies the HasPrefix predicate on the "content_hash" field.
func ContentHashHasPrefix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasPrefix(FieldContentHash, v))
}

// ContentHashHasSuffix applies the HasSuffix predicate on the "content_hash" field.
func ContentHashHasSuffix(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldHasSuffix(FieldContentHash, v))
}

// ContentHashEqualFold applies the EqualFold predicate on the "content_hash" field.
func ContentHashEqualFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEqualFold(FieldContentHash, v))
}

// ContentHashContainsFold applies the ContainsFold predicate on the "content_hash" field.
func ContentHashContainsFold(v string) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldContainsFold(FieldContentHash, v))
}

// FirstSeenAtEQ applies the EQ predicate on the "first_seen_at" field.
func FirstSeenAtEQ(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtNEQ applies the NEQ predicate on the "first_seen_at" field.
func FirstSeenAtNEQ(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtIn applies the In predicate on the "first_seen_at" field.
func FirstSeenAtIn(vs ...time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtNotIn applies the NotIn predicate on the "first_seen_at" field.
func FirstSeenAtNotIn(vs ...time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtGT applies the GT predicate on the "first_seen_at" field.
func FirstSeenAtGT(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldFirstSeenAt, v))
}

// FirstSeenAtGTE applies the GTE predicate on the "first_seen_at" field.
func FirstSeenAtGTE(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldFirstSeenAt, v))
}

// FirstSeenAtLT applies the LT predicate on the "first_seen_at" field.
func FirstSeenAtLT(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldFirstSeenAt, v))
}

// FirstSeenAtLTE applies the LTE predicate on the "first_seen_at" field.
func FirstSeenAtLTE(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldFirstSeenAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldLastSeenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAgents applies the HasEdge predicate on the "agents" edge.
func HasAgents() predicate.TeamDefinition {
	return predicate.TeamDefinition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, AgentsTable, AgentsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentsWith applies the HasEdge predicate on the "agents" edge with a given conditions (other predicates).
func HasAgentsWith(preds ...predicate.AgentDefinition) predicate.TeamDefinition {
	return predicate.TeamDefinition(func(s *sql.Selector) {
		step := newAgentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamDefinition) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamDefinition) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamDefinition) predicate.TeamDefinition {
	return predicate.TeamDefinition(sql.NotPredicates(p))
}
