// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/agentplexus/internal/ent/agentdefinition"
	"github.com/plexusone/agentplexus/internal/ent/teamdefinition"
)

// AgentDefinitionCreate is the builder for creating a AgentDefinition entity.
type AgentDefinitionCreate struct {
	config
	mutation *AgentDefinitionMutation
	hooks    []Hook
}

// SetRepoName sets the "repo_name" field.
func (_c *AgentDefinitionCreate) SetRepoName(v string) *AgentDefinitionCreate {
	_c.mutation.SetRepoName(v)
	return _c
}

// SetNamespace sets the "namespace" field.
func (_c *AgentDefinitionCreate) SetNamespace(v string) *AgentDefinitionCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableNamespace(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetNamespace(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AgentDefinitionCreate) SetName(v string) *AgentDefinitionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetQualifiedName sets the "qualified_name" field.
func (_c *AgentDefinitionCreate) SetQualifiedName(v string) *AgentDefinitionCreate {
	_c.mutation.SetQualifiedName(v)
	return _c
}

// SetSourceRef sets the "source_ref" field.
func (_c *AgentDefinitionCreate) SetSourceRef(v string) *AgentDefinitionCreate {
	_c.mutation.SetSourceRef(v)
	return _c
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableSourceRef(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetSourceRef(*v)
	}
	return _c
}

// SetRegistryXrn sets the "registry_xrn" field.
func (_c *AgentDefinitionCreate) SetRegistryXrn(v string) *AgentDefinitionCreate {
	_c.mutation.SetRegistryXrn(v)
	return _c
}

// SetNillableRegistryXrn sets the "registry_xrn" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableRegistryXrn(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetRegistryXrn(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *AgentDefinitionCreate) SetDescription(v string) *AgentDefinitionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableDescription(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *AgentDefinitionCreate) SetModel(v string) *AgentDefinitionCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableModel(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *AgentDefinitionCreate) SetIcon(v string) *AgentDefinitionCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableIcon(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *AgentDefinitionCreate) SetRole(v string) *AgentDefinitionCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableRole(v *string) *AgentDefinitionCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetTools sets the "tools" field.
func (_c *AgentDefinitionCreate) SetTools(v []string) *AgentDefinitionCreate {
	_c.mutation.SetTools(v)
	return _c
}

// SetAllowedTools sets the "allowed_tools" field.
func (_c *AgentDefinitionCreate) SetAllowedTools(v []string) *AgentDefinitionCreate {
	_c.mutation.SetAllowedTools(v)
	return _c
}

// SetSkills sets the "skills" field.
func (_c *AgentDefinitionCreate) SetSkills(v []string) *AgentDefinitionCreate {
	_c.mutation.SetSkills(v)
	return _c
}

// SetDependencies sets the "dependencies" field.
func (_c *AgentDefinitionCreate) SetDependencies(v []string) *AgentDefinitionCreate {
	_c.mutation.SetDependencies(v)
	return _c
}

// SetRequires sets the "requires" field.
func (_c *AgentDefinitionCreate) SetRequires(v []string) *AgentDefinitionCreate {
	_c.mutation.SetRequires(v)
	return _c
}

// SetSourcePath sets the "source_path" field.
func (_c *AgentDefinitionCreate) SetSourcePath(v string) *AgentDefinitionCreate {
	_c.mutation.SetSourcePath(v)
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *AgentDefinitionCreate) SetContentHash(v string) *AgentDefinitionCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_c *AgentDefinitionCreate) SetFirstSeenAt(v time.Time) *AgentDefinitionCreate {
	_c.mutation.SetFirstSeenAt(v)
	return _c
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableFirstSeenAt(v *time.Time) *AgentDefinitionCreate {
	if v != nil {
		_c.SetFirstSeenAt(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *AgentDefinitionCreate) SetLastSeenAt(v time.Time) *AgentDefinitionCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableLastSeenAt(v *time.Time) *AgentDefinitionCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentDefinitionCreate) SetCreatedAt(v time.Time) *AgentDefinitionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableCreatedAt(v *time.Time) *AgentDefinitionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentDefinitionCreate) SetUpdatedAt(v time.Time) *AgentDefinitionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableUpdatedAt(v *time.Time) *AgentDefinitionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentDefinitionCreate) SetID(v uuid.UUID) *AgentDefinitionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AgentDefinitionCreate) SetNillableID(v *uuid.UUID) *AgentDefinitionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTeamIDs adds the "teams" edge to the TeamDefinition entity by IDs.
func (_c *AgentDefinitionCreate) AddTeamIDs(ids ...uuid.UUID) *AgentDefinitionCreate {
	_c.mutation.AddTeamIDs(ids...)
	return _c
}

// AddTeams adds the "teams" edges to the TeamDefinition entity.
func (_c *AgentDefinitionCreate) AddTeams(v ...*TeamDefinition) *AgentDefinitionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeamIDs(ids...)
}

// Mutation returns the AgentDefinitionMutation object of the builder.
func (_c *AgentDefinitionCreate) Mutation() *AgentDefinitionMutation {
	return _c.mutation
}

// Save creates the AgentDefinition in the database.
func (_c *AgentDefinitionCreate) Save(ctx context.Context) (*AgentDefinition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentDefinitionCreate) SaveX(ctx context.Context) *AgentDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentDefinitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentDefinitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentDefinitionCreate) defaults() {
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		v := agentdefinition.DefaultFirstSeenAt()
		_c.mutation.SetFirstSeenAt(v)
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := agentdefinition.DefaultLastSeenAt()
		_c.mutation.SetLastSeenAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agentdefinition.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agentdefinition.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := agentdefinition.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentDefinitionCreate) check() error {
	if _, ok := _c.mutation.RepoName(); !ok {
		return &ValidationError{Name: "repo_name", err: errors.New(`ent: missing required field "AgentDefinition.repo_name"`)}
	}
	if v, ok := _c.mutation.RepoName(); ok {
		if err := agentdefinition.RepoNameValidator(v); err != nil {
			return &ValidationError{Name: "repo_name", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.repo_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AgentDefinition.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := agentdefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QualifiedName(); !ok {
		return &ValidationError{Name: "qualified_name", err: errors.New(`ent: missing required field "AgentDefinition.qualified_name"`)}
	}
	if v, ok := _c.mutation.QualifiedName(); ok {
		if err := agentdefinition.QualifiedNameValidator(v); err != nil {
			return &ValidationError{Name: "qualified_name", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.qualified_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourcePath(); !ok {
		return &ValidationError{Name: "source_path", err: errors.New(`ent: missing required field "AgentDefinition.source_path"`)}
	}
	if v, ok := _c.mutation.SourcePath(); ok {
		if err := agentdefinition.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.source_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentHash(); !ok {
		return &ValidationError{Name: "content_hash", err: errors.New(`ent: missing required field "AgentDefinition.content_hash"`)}
	}
	if v, ok := _c.mutation.ContentHash(); ok {
		if err := agentdefinition.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.content_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		return &ValidationError{Name: "first_seen_at", err: errors.New(`ent: missing required field "AgentDefinition.first_seen_at"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "AgentDefinition.last_seen_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentDefinition.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AgentDefinition.updated_at"`)}
	}
	return nil
}

func (_c *AgentDefinitionCreate) sqlSave(ctx context.Context) (*AgentDefinition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentDefinitionCreate) createSpec() (*AgentDefinition, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentDefinition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentdefinition.Table, sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RepoName(); ok {
		_spec.SetField(agentdefinition.FieldRepoName, field.TypeString, value)
		_node.RepoName = value
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(agentdefinition.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(agentdefinition.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.QualifiedName(); ok {
		_spec.SetField(agentdefinition.FieldQualifiedName, field.TypeString, value)
		_node.QualifiedName = value
	}
	if value, ok := _c.mutation.SourceRef(); ok {
		_spec.SetField(agentdefinition.FieldSourceRef, field.TypeString, value)
		_node.SourceRef = value
	}
	if value, ok := _c.mutation.RegistryXrn(); ok {
		_spec.SetField(agentdefinition.FieldRegistryXrn, field.TypeString, value)
		_node.RegistryXrn = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(agentdefinition.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(agentdefinition.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(agentdefinition.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(agentdefinition.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Tools(); ok {
		_spec.SetField(agentdefinition.FieldTools, field.TypeJSON, value)
		_node.Tools = value
	}
	if value, ok := _c.mutation.AllowedTools(); ok {
		_spec.SetField(agentdefinition.FieldAllowedTools, field.TypeJSON, value)
		_node.AllowedTools = value
	}
	if value, ok := _c.mutation.Skills(); ok {
		_spec.SetField(agentdefinition.FieldSkills, field.TypeJSON, value)
		_node.Skills = value
	}
	if value, ok := _c.mutation.Dependencies(); ok {
		_spec.SetField(agentdefinition.FieldDependencies, field.TypeJSON, value)
		_node.Dependencies = value
	}
	if value, ok := _c.mutation.Requires(); ok {
		_spec.SetField(agentdefinition.FieldRequires, field.TypeJSON, value)
		_node.Requires = value
	}
	if value, ok := _c.mutation.SourcePath(); ok {
		_spec.SetField(agentdefinition.FieldSourcePath, field.TypeString, value)
		_node.SourcePath = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(agentdefinition.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.FirstSeenAt(); ok {
		_spec.SetField(agentdefinition.FieldFirstSeenAt, field.TypeTime, value)
		_node.FirstSeenAt = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(agentdefinition.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentdefinition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agentdefinition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agentdefinition.TeamsTable,
			Columns: agentdefinition.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentDefinitionCreateBulk is the builder for creating many AgentDefinition entities in bulk.
type AgentDefinitionCreateBulk struct {
	config
	err      error
	builders []*AgentDefinitionCreate
}

// Save creates the AgentDefinition entities in the database.
func (_c *AgentDefinitionCreateBulk) Save(ctx context.Context) ([]*AgentDefinition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentDefinition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentDefinitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentDefinitionCreateBulk) SaveX(ctx context.Context) []*AgentDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentDefinitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentDefinitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
