// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/agentplexus/internal/ent/agentdefinition"
	"github.com/plexusone/agentplexus/internal/ent/predicate"
)

// AgentDefinitionDelete is the builder for deleting a AgentDefinition entity.
type AgentDefinitionDelete struct {
	config
	hooks    []Hook
	mutation *AgentDefinitionMutation
}

// Where appends a list predicates to the AgentDefinitionDelete builder.
func (_d *AgentDefinitionDelete) Where(ps ...predicate.AgentDefinition) *AgentDefinitionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AgentDefinitionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentDefinitionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AgentDefinitionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agentdefinition.Table, sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AgentDefinitionDeleteOne is the builder for deleting a single AgentDefinition entity.
type AgentDefinitionDeleteOne struct {
	_d *AgentDefinitionDelete
}

// Where appends a list predicates to the AgentDefinitionDelete builder.
func (_d *AgentDefinitionDeleteOne) Where(ps ...predicate.AgentDefinition) *AgentDefinitionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AgentDefinitionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agentdefinition.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentDefinitionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
