// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/agentplexus/internal/ent/agentdefinition"
	"github.com/plexusone/agentplexus/internal/ent/predicate"
	"github.com/plexusone/agentplexus/internal/ent/teamdefinition"
)

// AgentDefinitionUpdate is the builder for updating AgentDefinition entities.
type AgentDefinitionUpdate struct {
	config
	hooks    []Hook
	mutation *AgentDefinitionMutation
}

// Where appends a list predicates to the AgentDefinitionUpdate builder.
func (_u *AgentDefinitionUpdate) Where(ps ...predicate.AgentDefinition) *AgentDefinitionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRepoName sets the "repo_name" field.
func (_u *AgentDefinitionUpdate) SetRepoName(v string) *AgentDefinitionUpdate {
	_u.mutation.SetRepoName(v)
	return _u
}

// SetNillableRepoName sets the "repo_name" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableRepoName(v *string) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetRepoName(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *AgentDefinitionUpdate) SetNamespace(v string) *AgentDefinitionUpdate {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableNamespace(v *string) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AgentDefinitionUpdate) SetName(v string) *AgentDefinitionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableName(v *string) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetQualifiedName sets the "qualified_name" field.
func (_u *AgentDefinitionUpdate) SetQualifiedName(v string) *AgentDefinitionUpdate {
	_u.mutation.SetQualifiedName(v)
	return _u
}

// SetNillableQualifiedName sets the "qualified_name" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableQualifiedName(v *string) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetQualifiedName(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *AgentDefinitionUpdate) SetSourceRef(v string) *AgentDefinitionUpdate {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableSourceRef(v *string) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (_u *AgentDefinitionUpdate) ClearSourceRef() *AgentDefinitionUpdate {
	_u.mutation.ClearSourceRef()
	return _u
}

// SetDescription sets the "description" field.
func (_u *AgentDefinitionUpdate) SetDescription(v string) *AgentDefinitionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableDescription(v *string) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AgentDefinitionUpdate) ClearDescription() *AgentDefinitionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetModel sets the "model" field.
func (_u *AgentDefinitionUpdate) SetModel(v string) *AgentDefinitionUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableModel(v *string) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *AgentDefinitionUpdate) ClearModel() *AgentDefinitionUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetIcon sets the "icon" field.
func (_u *AgentDefinitionUpdate) SetIcon(v string) *AgentDefinitionUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableIcon(v *string) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *AgentDefinitionUpdate) ClearIcon() *AgentDefinitionUpdate {
	_u.mutation.ClearIcon()
	return _u
}

// SetRole sets the "role" field.
func (_u *AgentDefinitionUpdate) SetRole(v string) *AgentDefinitionUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableRole(v *string) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// ClearRole clears the value of the "role" field.
func (_u *AgentDefinitionUpdate) ClearRole() *AgentDefinitionUpdate {
	_u.mutation.ClearRole()
	return _u
}

// SetTools sets the "tools" field.
func (_u *AgentDefinitionUpdate) SetTools(v []string) *AgentDefinitionUpdate {
	_u.mutation.SetTools(v)
	return _u
}

// AppendTools appends value to the "tools" field.
func (_u *AgentDefinitionUpdate) AppendTools(v []string) *AgentDefinitionUpdate {
	_u.mutation.AppendTools(v)
	return _u
}

// ClearTools clears the value of the "tools" field.
func (_u *AgentDefinitionUpdate) ClearTools() *AgentDefinitionUpdate {
	_u.mutation.ClearTools()
	return _u
}

// SetAllowedTools sets the "allowed_tools" field.
func (_u *AgentDefinitionUpdate) SetAllowedTools(v []string) *AgentDefinitionUpdate {
	_u.mutation.SetAllowedTools(v)
	return _u
}

// AppendAllowedTools appends value to the "allowed_tools" field.
func (_u *AgentDefinitionUpdate) AppendAllowedTools(v []string) *AgentDefinitionUpdate {
	_u.mutation.AppendAllowedTools(v)
	return _u
}

// ClearAllowedTools clears the value of the "allowed_tools" field.
func (_u *AgentDefinitionUpdate) ClearAllowedTools() *AgentDefinitionUpdate {
	_u.mutation.ClearAllowedTools()
	return _u
}

// SetSkills sets the "skills" field.
func (_u *AgentDefinitionUpdate) SetSkills(v []string) *AgentDefinitionUpdate {
	_u.mutation.SetSkills(v)
	return _u
}

// AppendSkills appends value to the "skills" field.
func (_u *AgentDefinitionUpdate) AppendSkills(v []string) *AgentDefinitionUpdate {
	_u.mutation.AppendSkills(v)
	return _u
}

// ClearSkills clears the value of the "skills" field.
func (_u *AgentDefinitionUpdate) ClearSkills() *AgentDefinitionUpdate {
	_u.mutation.ClearSkills()
	return _u
}

// SetDependencies sets the "dependencies" field.
func (_u *AgentDefinitionUpdate) SetDependencies(v []string) *AgentDefinitionUpdate {
	_u.mutation.SetDependencies(v)
	return _u
}

// AppendDependencies appends value to the "dependencies" field.
func (_u *AgentDefinitionUpdate) AppendDependencies(v []string) *AgentDefinitionUpdate {
	_u.mutation.AppendDependencies(v)
	return _u
}

// ClearDependencies clears the value of the "dependencies" field.
func (_u *AgentDefinitionUpdate) ClearDependencies() *AgentDefinitionUpdate {
	_u.mutation.ClearDependencies()
	return _u
}

// SetRequires sets the "requires" field.
func (_u *AgentDefinitionUpdate) SetRequires(v []string) *AgentDefinitionUpdate {
	_u.mutation.SetRequires(v)
	return _u
}

// AppendRequires appends value to the "requires" field.
func (_u *AgentDefinitionUpdate) AppendRequires(v []string) *AgentDefinitionUpdate {
	_u.mutation.AppendRequires(v)
	return _u
}

// ClearRequires clears the value of the "requires" field.
func (_u *AgentDefinitionUpdate) ClearRequires() *AgentDefinitionUpdate {
	_u.mutation.ClearRequires()
	return _u
}

// SetSourcePath sets the "source_path" field.
func (_u *AgentDefinitionUpdate) SetSourcePath(v string) *AgentDefinitionUpdate {
	_u.mutation.SetSourcePath(v)
	return _u
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableSourcePath(v *string) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetSourcePath(*v)
	}
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *AgentDefinitionUpdate) SetContentHash(v string) *AgentDefinitionUpdate {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableContentHash(v *string) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AgentDefinitionUpdate) SetLastSeenAt(v time.Time) *AgentDefinitionUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AgentDefinitionUpdate) SetNillableLastSeenAt(v *time.Time) *AgentDefinitionUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentDefinitionUpdate) SetUpdatedAt(v time.Time) *AgentDefinitionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTeamIDs adds the "teams" edge to the TeamDefinition entity by IDs.
func (_u *AgentDefinitionUpdate) AddTeamIDs(ids ...uuid.UUID) *AgentDefinitionUpdate {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the TeamDefinition entity.
func (_u *AgentDefinitionUpdate) AddTeams(v ...*TeamDefinition) *AgentDefinitionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// Mutation returns the AgentDefinitionMutation object of the builder.
func (_u *AgentDefinitionUpdate) Mutation() *AgentDefinitionMutation {
	return _u.mutation
}

// ClearTeams clears all "teams" edges to the TeamDefinition entity.
func (_u *AgentDefinitionUpdate) ClearTeams() *AgentDefinitionUpdate {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to TeamDefinition entities by IDs.
func (_u *AgentDefinitionUpdate) RemoveTeamIDs(ids ...uuid.UUID) *AgentDefinitionUpdate {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to TeamDefinition entities.
func (_u *AgentDefinitionUpdate) RemoveTeams(v ...*TeamDefinition) *AgentDefinitionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentDefinitionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentDefinitionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentDefinitionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentDefinitionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentDefinitionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentdefinition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentDefinitionUpdate) check() error {
	if v, ok := _u.mutation.RepoName(); ok {
		if err := agentdefinition.RepoNameValidator(v); err != nil {
			return &ValidationError{Name: "repo_name", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.repo_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := agentdefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QualifiedName(); ok {
		if err := agentdefinition.QualifiedNameValidator(v); err != nil {
			return &ValidationError{Name: "qualified_name", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.qualified_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourcePath(); ok {
		if err := agentdefinition.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.source_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := agentdefinition.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.content_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentDefinitionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentdefinition.Table, agentdefinition.Columns, sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoName(); ok {
		_spec.SetField(agentdefinition.FieldRepoName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(agentdefinition.FieldNamespace, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentdefinition.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.QualifiedName(); ok {
		_spec.SetField(agentdefinition.FieldQualifiedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(agentdefinition.FieldSourceRef, field.TypeString, value)
	}
	if _u.mutation.SourceRefCleared() {
		_spec.ClearField(agentdefinition.FieldSourceRef, field.TypeString)
	}
	if _u.mutation.RegistryXrnCleared() {
		_spec.ClearField(agentdefinition.FieldRegistryXrn, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(agentdefinition.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(agentdefinition.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(agentdefinition.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(agentdefinition.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(agentdefinition.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(agentdefinition.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(agentdefinition.FieldRole, field.TypeString, value)
	}
	if _u.mutation.RoleCleared() {
		_spec.ClearField(agentdefinition.FieldRole, field.TypeString)
	}
	if value, ok := _u.mutation.Tools(); ok {
		_spec.SetField(agentdefinition.FieldTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentdefinition.FieldTools, value)
		})
	}
	if _u.mutation.ToolsCleared() {
		_spec.ClearField(agentdefinition.FieldTools, field.TypeJSON)
	}
	if value, ok := _u.mutation.AllowedTools(); ok {
		_spec.SetField(agentdefinition.FieldAllowedTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentdefinition.FieldAllowedTools, value)
		})
	}
	if _u.mutation.AllowedToolsCleared() {
		_spec.ClearField(agentdefinition.FieldAllowedTools, field.TypeJSON)
	}
	if value, ok := _u.mutation.Skills(); ok {
		_spec.SetField(agentdefinition.FieldSkills, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkills(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentdefinition.FieldSkills, value)
		})
	}
	if _u.mutation.SkillsCleared() {
		_spec.ClearField(agentdefinition.FieldSkills, field.TypeJSON)
	}
	if value, ok := _u.mutation.Dependencies(); ok {
		_spec.SetField(agentdefinition.FieldDependencies, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDependencies(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentdefinition.FieldDependencies, value)
		})
	}
	if _u.mutation.DependenciesCleared() {
		_spec.ClearField(agentdefinition.FieldDependencies, field.TypeJSON)
	}
	if value, ok := _u.mutation.Requires(); ok {
		_spec.SetField(agentdefinition.FieldRequires, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequires(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentdefinition.FieldRequires, value)
		})
	}
	if _u.mutation.RequiresCleared() {
		_spec.ClearField(agentdefinition.FieldRequires, field.TypeJSON)
	}
	if value, ok := _u.mutation.SourcePath(); ok {
		_spec.SetField(agentdefinition.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(agentdefinition.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(agentdefinition.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentdefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agentdefinition.TeamsTable,
			Columns: agentdefinition.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdefinition.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agentdefinition.TeamsTable,
			Columns: agentdefinition.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agentdefinition.TeamsTable,
			Columns: agentdefinition.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentdefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentDefinitionUpdateOne is the builder for updating a single AgentDefinition entity.
type AgentDefinitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentDefinitionMutation
}

// SetRepoName sets the "repo_name" field.
func (_u *AgentDefinitionUpdateOne) SetRepoName(v string) *AgentDefinitionUpdateOne {
	_u.mutation.SetRepoName(v)
	return _u
}

// SetNillableRepoName sets the "repo_name" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableRepoName(v *string) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetRepoName(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *AgentDefinitionUpdateOne) SetNamespace(v string) *AgentDefinitionUpdateOne {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableNamespace(v *string) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AgentDefinitionUpdateOne) SetName(v string) *AgentDefinitionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableName(v *string) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetQualifiedName sets the "qualified_name" field.
func (_u *AgentDefinitionUpdateOne) SetQualifiedName(v string) *AgentDefinitionUpdateOne {
	_u.mutation.SetQualifiedName(v)
	return _u
}

// SetNillableQualifiedName sets the "qualified_name" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableQualifiedName(v *string) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetQualifiedName(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *AgentDefinitionUpdateOne) SetSourceRef(v string) *AgentDefinitionUpdateOne {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableSourceRef(v *string) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (_u *AgentDefinitionUpdateOne) ClearSourceRef() *AgentDefinitionUpdateOne {
	_u.mutation.ClearSourceRef()
	return _u
}

// SetDescription sets the "description" field.
func (_u *AgentDefinitionUpdateOne) SetDescription(v string) *AgentDefinitionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableDescription(v *string) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AgentDefinitionUpdateOne) ClearDescription() *AgentDefinitionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetModel sets the "model" field.
func (_u *AgentDefinitionUpdateOne) SetModel(v string) *AgentDefinitionUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableModel(v *string) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *AgentDefinitionUpdateOne) ClearModel() *AgentDefinitionUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetIcon sets the "icon" field.
func (_u *AgentDefinitionUpdateOne) SetIcon(v string) *AgentDefinitionUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableIcon(v *string) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *AgentDefinitionUpdateOne) ClearIcon() *AgentDefinitionUpdateOne {
	_u.mutation.ClearIcon()
	return _u
}

// SetRole sets the "role" field.
func (_u *AgentDefinitionUpdateOne) SetRole(v string) *AgentDefinitionUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableRole(v *string) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// ClearRole clears the value of the "role" field.
func (_u *AgentDefinitionUpdateOne) ClearRole() *AgentDefinitionUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// SetTools sets the "tools" field.
func (_u *AgentDefinitionUpdateOne) SetTools(v []string) *AgentDefinitionUpdateOne {
	_u.mutation.SetTools(v)
	return _u
}

// AppendTools appends value to the "tools" field.
func (_u *AgentDefinitionUpdateOne) AppendTools(v []string) *AgentDefinitionUpdateOne {
	_u.mutation.AppendTools(v)
	return _u
}

// ClearTools clears the value of the "tools" field.
func (_u *AgentDefinitionUpdateOne) ClearTools() *AgentDefinitionUpdateOne {
	_u.mutation.ClearTools()
	return _u
}

// SetAllowedTools sets the "allowed_tools" field.
func (_u *AgentDefinitionUpdateOne) SetAllowedTools(v []string) *AgentDefinitionUpdateOne {
	_u.mutation.SetAllowedTools(v)
	return _u
}

// AppendAllowedTools appends value to the "allowed_tools" field.
func (_u *AgentDefinitionUpdateOne) AppendAllowedTools(v []string) *AgentDefinitionUpdateOne {
	_u.mutation.AppendAllowedTools(v)
	return _u
}

// ClearAllowedTools clears the value of the "allowed_tools" field.
func (_u *AgentDefinitionUpdateOne) ClearAllowedTools() *AgentDefinitionUpdateOne {
	_u.mutation.ClearAllowedTools()
	return _u
}

// SetSkills sets the "skills" field.
func (_u *AgentDefinitionUpdateOne) SetSkills(v []string) *AgentDefinitionUpdateOne {
	_u.mutation.SetSkills(v)
	return _u
}

// AppendSkills appends value to the "skills" field.
func (_u *AgentDefinitionUpdateOne) AppendSkills(v []string) *AgentDefinitionUpdateOne {
	_u.mutation.AppendSkills(v)
	return _u
}

// ClearSkills clears the value of the "skills" field.
func (_u *AgentDefinitionUpdateOne) ClearSkills() *AgentDefinitionUpdateOne {
	_u.mutation.ClearSkills()
	return _u
}

// SetDependencies sets the "dependencies" field.
func (_u *AgentDefinitionUpdateOne) SetDependencies(v []string) *AgentDefinitionUpdateOne {
	_u.mutation.SetDependencies(v)
	return _u
}

// AppendDependencies appends value to the "dependencies" field.
func (_u *AgentDefinitionUpdateOne) AppendDependencies(v []string) *AgentDefinitionUpdateOne {
	_u.mutation.AppendDependencies(v)
	return _u
}

// ClearDependencies clears the value of the "dependencies" field.
func (_u *AgentDefinitionUpdateOne) ClearDependencies() *AgentDefinitionUpdateOne {
	_u.mutation.ClearDependencies()
	return _u
}

// SetRequires sets the "requires" field.
func (_u *AgentDefinitionUpdateOne) SetRequires(v []string) *AgentDefinitionUpdateOne {
	_u.mutation.SetRequires(v)
	return _u
}

// AppendRequires appends value to the "requires" field.
func (_u *AgentDefinitionUpdateOne) AppendRequires(v []string) *AgentDefinitionUpdateOne {
	_u.mutation.AppendRequires(v)
	return _u
}

// ClearRequires clears the value of the "requires" field.
func (_u *AgentDefinitionUpdateOne) ClearRequires() *AgentDefinitionUpdateOne {
	_u.mutation.ClearRequires()
	return _u
}

// SetSourcePath sets the "source_path" field.
func (_u *AgentDefinitionUpdateOne) SetSourcePath(v string) *AgentDefinitionUpdateOne {
	_u.mutation.SetSourcePath(v)
	return _u
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableSourcePath(v *string) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetSourcePath(*v)
	}
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *AgentDefinitionUpdateOne) SetContentHash(v string) *AgentDefinitionUpdateOne {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableContentHash(v *string) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AgentDefinitionUpdateOne) SetLastSeenAt(v time.Time) *AgentDefinitionUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AgentDefinitionUpdateOne) SetNillableLastSeenAt(v *time.Time) *AgentDefinitionUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentDefinitionUpdateOne) SetUpdatedAt(v time.Time) *AgentDefinitionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTeamIDs adds the "teams" edge to the TeamDefinition entity by IDs.
func (_u *AgentDefinitionUpdateOne) AddTeamIDs(ids ...uuid.UUID) *AgentDefinitionUpdateOne {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the TeamDefinition entity.
func (_u *AgentDefinitionUpdateOne) AddTeams(v ...*TeamDefinition) *AgentDefinitionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// Mutation returns the AgentDefinitionMutation object of the builder.
func (_u *AgentDefinitionUpdateOne) Mutation() *AgentDefinitionMutation {
	return _u.mutation
}

// ClearTeams clears all "teams" edges to the TeamDefinition entity.
func (_u *AgentDefinitionUpdateOne) ClearTeams() *AgentDefinitionUpdateOne {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to TeamDefinition entities by IDs.
func (_u *AgentDefinitionUpdateOne) RemoveTeamIDs(ids ...uuid.UUID) *AgentDefinitionUpdateOne {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to TeamDefinition entities.
func (_u *AgentDefinitionUpdateOne) RemoveTeams(v ...*TeamDefinition) *AgentDefinitionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// Where appends a list predicates to the AgentDefinitionUpdate builder.
func (_u *AgentDefinitionUpdateOne) Where(ps ...predicate.AgentDefinition) *AgentDefinitionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentDefinitionUpdateOne) Select(field string, fields ...string) *AgentDefinitionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentDefinition entity.
func (_u *AgentDefinitionUpdateOne) Save(ctx context.Context) (*AgentDefinition, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentDefinitionUpdateOne) SaveX(ctx context.Context) *AgentDefinition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentDefinitionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentDefinitionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentDefinitionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentdefinition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentDefinitionUpdateOne) check() error {
	if v, ok := _u.mutation.RepoName(); ok {
		if err := agentdefinition.RepoNameValidator(v); err != nil {
			return &ValidationError{Name: "repo_name", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.repo_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := agentdefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QualifiedName(); ok {
		if err := agentdefinition.QualifiedNameValidator(v); err != nil {
			return &ValidationError{Name: "qualified_name", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.qualified_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourcePath(); ok {
		if err := agentdefinition.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.source_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := agentdefinition.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "AgentDefinition.content_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentDefinitionUpdateOne) sqlSave(ctx context.Context) (_node *AgentDefinition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentdefinition.Table, agentdefinition.Columns, sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentDefinition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentdefinition.FieldID)
		for _, f := range fields {
			if !agentdefinition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentdefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoName(); ok {
		_spec.SetField(agentdefinition.FieldRepoName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(agentdefinition.FieldNamespace, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentdefinition.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.QualifiedName(); ok {
		_spec.SetField(agentdefinition.FieldQualifiedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(agentdefinition.FieldSourceRef, field.TypeString, value)
	}
	if _u.mutation.SourceRefCleared() {
		_spec.ClearField(agentdefinition.FieldSourceRef, field.TypeString)
	}
	if _u.mutation.RegistryXrnCleared() {
		_spec.ClearField(agentdefinition.FieldRegistryXrn, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(agentdefinition.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(agentdefinition.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(agentdefinition.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(agentdefinition.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(agentdefinition.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(agentdefinition.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(agentdefinition.FieldRole, field.TypeString, value)
	}
	if _u.mutation.RoleCleared() {
		_spec.ClearField(agentdefinition.FieldRole, field.TypeString)
	}
	if value, ok := _u.mutation.Tools(); ok {
		_spec.SetField(agentdefinition.FieldTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentdefinition.FieldTools, value)
		})
	}
	if _u.mutation.ToolsCleared() {
		_spec.ClearField(agentdefinition.FieldTools, field.TypeJSON)
	}
	if value, ok := _u.mutation.AllowedTools(); ok {
		_spec.SetField(agentdefinition.FieldAllowedTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentdefinition.FieldAllowedTools, value)
		})
	}
	if _u.mutation.AllowedToolsCleared() {
		_spec.ClearField(agentdefinition.FieldAllowedTools, field.TypeJSON)
	}
	if value, ok := _u.mutation.Skills(); ok {
		_spec.SetField(agentdefinition.FieldSkills, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkills(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentdefinition.FieldSkills, value)
		})
	}
	if _u.mutation.SkillsCleared() {
		_spec.ClearField(agentdefinition.FieldSkills, field.TypeJSON)
	}
	if value, ok := _u.mutation.Dependencies(); ok {
		_spec.SetField(agentdefinition.FieldDependencies, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDependencies(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentdefinition.FieldDependencies, value)
		})
	}
	if _u.mutation.DependenciesCleared() {
		_spec.ClearField(agentdefinition.FieldDependencies, field.TypeJSON)
	}
	if value, ok := _u.mutation.Requires(); ok {
		_spec.SetField(agentdefinition.FieldRequires, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequires(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentdefinition.FieldRequires, value)
		})
	}
	if _u.mutation.RequiresCleared() {
		_spec.ClearField(agentdefinition.FieldRequires, field.TypeJSON)
	}
	if value, ok := _u.mutation.SourcePath(); ok {
		_spec.SetField(agentdefinition.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(agentdefinition.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(agentdefinition.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentdefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agentdefinition.TeamsTable,
			Columns: agentdefinition.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdefinition.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agentdefinition.TeamsTable,
			Columns: agentdefinition.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agentdefinition.TeamsTable,
			Columns: agentdefinition.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentDefinition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentdefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
