// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/agentplexus/internal/ent/agentdefinition"
)

// AgentDefinition is the model entity for the AgentDefinition schema.
type AgentDefinition struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Owning repository, e.g. agent-team-release
	RepoName string `json:"repo_name,omitempty"`
	// Subdirectory namespace, if any
	Namespace string `json:"namespace,omitempty"`
	// Agent name from spec frontmatter
	Name string `json:"name,omitempty"`
	// repo_name/namespace/name, for display and lookup
	QualifiedName string `json:"qualified_name,omitempty"`
	// User-facing Go-style source path, e.g. github.com/plexusone/agent-team-release/agents/release-reviewer
	SourceRef string `json:"source_ref,omitempty"`
	// Internal registry identity, xrn:agentplexus:agent-definition:<id>
	RegistryXrn string `json:"registry_xrn,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Icon holds the value of the "icon" field.
	Icon string `json:"icon,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Tools holds the value of the "tools" field.
	Tools []string `json:"tools,omitempty"`
	// AllowedTools holds the value of the "allowed_tools" field.
	AllowedTools []string `json:"allowed_tools,omitempty"`
	// Skills holds the value of the "skills" field.
	Skills []string `json:"skills,omitempty"`
	// Dependencies holds the value of the "dependencies" field.
	Dependencies []string `json:"dependencies,omitempty"`
	// Requires holds the value of the "requires" field.
	Requires []string `json:"requires,omitempty"`
	// Absolute path to the agent markdown file
	SourcePath string `json:"source_path,omitempty"`
	// sha256 of the source file, for drift detection
	ContentHash string `json:"content_hash,omitempty"`
	// FirstSeenAt holds the value of the "first_seen_at" field.
	FirstSeenAt time.Time `json:"first_seen_at,omitempty"`
	// Updated on every successful registration sync
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentDefinitionQuery when eager-loading is set.
	Edges        AgentDefinitionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentDefinitionEdges holds the relations/edges for other nodes in the graph.
type AgentDefinitionEdges struct {
	// Teams holds the value of the teams edge.
	Teams []*TeamDefinition `json:"teams,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TeamsOrErr returns the Teams value or an error if the edge
// was not loaded in eager-loading.
func (e AgentDefinitionEdges) TeamsOrErr() ([]*TeamDefinition, error) {
	if e.loadedTypes[0] {
		return e.Teams, nil
	}
	return nil, &NotLoadedError{edge: "teams"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentDefinition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentdefinition.FieldTools, agentdefinition.FieldAllowedTools, agentdefinition.FieldSkills, agentdefinition.FieldDependencies, agentdefinition.FieldRequires:
			values[i] = new([]byte)
		case agentdefinition.FieldRepoName, agentdefinition.FieldNamespace, agentdefinition.FieldName, agentdefinition.FieldQualifiedName, agentdefinition.FieldSourceRef, agentdefinition.FieldRegistryXrn, agentdefinition.FieldDescription, agentdefinition.FieldModel, agentdefinition.FieldIcon, agentdefinition.FieldRole, agentdefinition.FieldSourcePath, agentdefinition.FieldContentHash:
			values[i] = new(sql.NullString)
		case agentdefinition.FieldFirstSeenAt, agentdefinition.FieldLastSeenAt, agentdefinition.FieldCreatedAt, agentdefinition.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case agentdefinition.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentDefinition fields.
func (_m *AgentDefinition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentdefinition.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case agentdefinition.FieldRepoName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_name", values[i])
			} else if value.Valid {
				_m.RepoName = value.String
			}
		case agentdefinition.FieldNamespace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field namespace", values[i])
			} else if value.Valid {
				_m.Namespace = value.String
			}
		case agentdefinition.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case agentdefinition.FieldQualifiedName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qualified_name", values[i])
			} else if value.Valid {
				_m.QualifiedName = value.String
			}
		case agentdefinition.FieldSourceRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_ref", values[i])
			} else if value.Valid {
				_m.SourceRef = value.String
			}
		case agentdefinition.FieldRegistryXrn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field registry_xrn", values[i])
			} else if value.Valid {
				_m.RegistryXrn = value.String
			}
		case agentdefinition.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case agentdefinition.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case agentdefinition.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = value.String
			}
		case agentdefinition.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case agentdefinition.FieldTools:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tools", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tools); err != nil {
					return fmt.Errorf("unmarshal field tools: %w", err)
				}
			}
		case agentdefinition.FieldAllowedTools:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_tools", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedTools); err != nil {
					return fmt.Errorf("unmarshal field allowed_tools: %w", err)
				}
			}
		case agentdefinition.FieldSkills:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field skills", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Skills); err != nil {
					return fmt.Errorf("unmarshal field skills: %w", err)
				}
			}
		case agentdefinition.FieldDependencies:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field dependencies", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Dependencies); err != nil {
					return fmt.Errorf("unmarshal field dependencies: %w", err)
				}
			}
		case agentdefinition.FieldRequires:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field requires", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Requires); err != nil {
					return fmt.Errorf("unmarshal field requires: %w", err)
				}
			}
		case agentdefinition.FieldSourcePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_path", values[i])
			} else if value.Valid {
				_m.SourcePath = value.String
			}
		case agentdefinition.FieldContentHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_hash", values[i])
			} else if value.Valid {
				_m.ContentHash = value.String
			}
		case agentdefinition.FieldFirstSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_seen_at", values[i])
			} else if value.Valid {
				_m.FirstSeenAt = value.Time
			}
		case agentdefinition.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case agentdefinition.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case agentdefinition.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentDefinition.
// This includes values selected through modifiers, order, etc.
func (_m *AgentDefinition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTeams queries the "teams" edge of the AgentDefinition entity.
func (_m *AgentDefinition) QueryTeams() *TeamDefinitionQuery {
	return NewAgentDefinitionClient(_m.config).QueryTeams(_m)
}

// Update returns a builder for updating this AgentDefinition.
// Note that you need to call AgentDefinition.Unwrap() before calling this method if this AgentDefinition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentDefinition) Update() *AgentDefinitionUpdateOne {
	return NewAgentDefinitionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentDefinition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentDefinition) Unwrap() *AgentDefinition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentDefinition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentDefinition) String() string {
	var builder strings.Builder
	builder.WriteString("AgentDefinition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("repo_name=")
	builder.WriteString(_m.RepoName)
	builder.WriteString(", ")
	builder.WriteString("namespace=")
	builder.WriteString(_m.Namespace)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("qualified_name=")
	builder.WriteString(_m.QualifiedName)
	builder.WriteString(", ")
	builder.WriteString("source_ref=")
	builder.WriteString(_m.SourceRef)
	builder.WriteString(", ")
	builder.WriteString("registry_xrn=")
	builder.WriteString(_m.RegistryXrn)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(_m.Icon)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("tools=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tools))
	builder.WriteString(", ")
	builder.WriteString("allowed_tools=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedTools))
	builder.WriteString(", ")
	builder.WriteString("skills=")
	builder.WriteString(fmt.Sprintf("%v", _m.Skills))
	builder.WriteString(", ")
	builder.WriteString("dependencies=")
	builder.WriteString(fmt.Sprintf("%v", _m.Dependencies))
	builder.WriteString(", ")
	builder.WriteString("requires=")
	builder.WriteString(fmt.Sprintf("%v", _m.Requires))
	builder.WriteString(", ")
	builder.WriteString("source_path=")
	builder.WriteString(_m.SourcePath)
	builder.WriteString(", ")
	builder.WriteString("content_hash=")
	builder.WriteString(_m.ContentHash)
	builder.WriteString(", ")
	builder.WriteString("first_seen_at=")
	builder.WriteString(_m.FirstSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AgentDefinitions is a parsable slice of AgentDefinition.
type AgentDefinitions []*AgentDefinition
