// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/plexusone/agentplexus/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/plexusone/agentplexus/internal/ent/agentdefinition"
	"github.com/plexusone/agentplexus/internal/ent/teamdefinition"
	"github.com/plexusone/agentplexus/internal/ent/view"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AgentDefinition is the client for interacting with the AgentDefinition builders.
	AgentDefinition *AgentDefinitionClient
	// TeamDefinition is the client for interacting with the TeamDefinition builders.
	TeamDefinition *TeamDefinitionClient
	// View is the client for interacting with the View builders.
	View *ViewClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AgentDefinition = NewAgentDefinitionClient(c.config)
	c.TeamDefinition = NewTeamDefinitionClient(c.config)
	c.View = NewViewClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		AgentDefinition: NewAgentDefinitionClient(cfg),
		TeamDefinition:  NewTeamDefinitionClient(cfg),
		View:            NewViewClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		AgentDefinition: NewAgentDefinitionClient(cfg),
		TeamDefinition:  NewTeamDefinitionClient(cfg),
		View:            NewViewClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AgentDefinition.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AgentDefinition.Use(hooks...)
	c.TeamDefinition.Use(hooks...)
	c.View.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.AgentDefinition.Intercept(interceptors...)
	c.TeamDefinition.Intercept(interceptors...)
	c.View.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AgentDefinitionMutation:
		return c.AgentDefinition.mutate(ctx, m)
	case *TeamDefinitionMutation:
		return c.TeamDefinition.mutate(ctx, m)
	case *ViewMutation:
		return c.View.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AgentDefinitionClient is a client for the AgentDefinition schema.
type AgentDefinitionClient struct {
	config
}

// NewAgentDefinitionClient returns a client for the AgentDefinition from the given config.
func NewAgentDefinitionClient(c config) *AgentDefinitionClient {
	return &AgentDefinitionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `agentdefinition.Hooks(f(g(h())))`.
func (c *AgentDefinitionClient) Use(hooks ...Hook) {
	c.hooks.AgentDefinition = append(c.hooks.AgentDefinition, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `agentdefinition.Intercept(f(g(h())))`.
func (c *AgentDefinitionClient) Intercept(interceptors ...Interceptor) {
	c.inters.AgentDefinition = append(c.inters.AgentDefinition, interceptors...)
}

// Create returns a builder for creating a AgentDefinition entity.
func (c *AgentDefinitionClient) Create() *AgentDefinitionCreate {
	mutation := newAgentDefinitionMutation(c.config, OpCreate)
	return &AgentDefinitionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AgentDefinition entities.
func (c *AgentDefinitionClient) CreateBulk(builders ...*AgentDefinitionCreate) *AgentDefinitionCreateBulk {
	return &AgentDefinitionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AgentDefinitionClient) MapCreateBulk(slice any, setFunc func(*AgentDefinitionCreate, int)) *AgentDefinitionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AgentDefinitionCreateBulk{err: fmt.Errorf("calling to AgentDefinitionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AgentDefinitionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AgentDefinitionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AgentDefinition.
func (c *AgentDefinitionClient) Update() *AgentDefinitionUpdate {
	mutation := newAgentDefinitionMutation(c.config, OpUpdate)
	return &AgentDefinitionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AgentDefinitionClient) UpdateOne(_m *AgentDefinition) *AgentDefinitionUpdateOne {
	mutation := newAgentDefinitionMutation(c.config, OpUpdateOne, withAgentDefinition(_m))
	return &AgentDefinitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AgentDefinitionClient) UpdateOneID(id uuid.UUID) *AgentDefinitionUpdateOne {
	mutation := newAgentDefinitionMutation(c.config, OpUpdateOne, withAgentDefinitionID(id))
	return &AgentDefinitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AgentDefinition.
func (c *AgentDefinitionClient) Delete() *AgentDefinitionDelete {
	mutation := newAgentDefinitionMutation(c.config, OpDelete)
	return &AgentDefinitionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AgentDefinitionClient) DeleteOne(_m *AgentDefinition) *AgentDefinitionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AgentDefinitionClient) DeleteOneID(id uuid.UUID) *AgentDefinitionDeleteOne {
	builder := c.Delete().Where(agentdefinition.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AgentDefinitionDeleteOne{builder}
}

// Query returns a query builder for AgentDefinition.
func (c *AgentDefinitionClient) Query() *AgentDefinitionQuery {
	return &AgentDefinitionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAgentDefinition},
		inters: c.Interceptors(),
	}
}

// Get returns a AgentDefinition entity by its id.
func (c *AgentDefinitionClient) Get(ctx context.Context, id uuid.UUID) (*AgentDefinition, error) {
	return c.Query().Where(agentdefinition.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AgentDefinitionClient) GetX(ctx context.Context, id uuid.UUID) *AgentDefinition {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTeams queries the teams edge of a AgentDefinition.
func (c *AgentDefinitionClient) QueryTeams(_m *AgentDefinition) *TeamDefinitionQuery {
	query := (&TeamDefinitionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(agentdefinition.Table, agentdefinition.FieldID, id),
			sqlgraph.To(teamdefinition.Table, teamdefinition.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, agentdefinition.TeamsTable, agentdefinition.TeamsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AgentDefinitionClient) Hooks() []Hook {
	return c.hooks.AgentDefinition
}

// Interceptors returns the client interceptors.
func (c *AgentDefinitionClient) Interceptors() []Interceptor {
	return c.inters.AgentDefinition
}

func (c *AgentDefinitionClient) mutate(ctx context.Context, m *AgentDefinitionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AgentDefinitionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AgentDefinitionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AgentDefinitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AgentDefinitionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AgentDefinition mutation op: %q", m.Op())
	}
}

// TeamDefinitionClient is a client for the TeamDefinition schema.
type TeamDefinitionClient struct {
	config
}

// NewTeamDefinitionClient returns a client for the TeamDefinition from the given config.
func NewTeamDefinitionClient(c config) *TeamDefinitionClient {
	return &TeamDefinitionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `teamdefinition.Hooks(f(g(h())))`.
func (c *TeamDefinitionClient) Use(hooks ...Hook) {
	c.hooks.TeamDefinition = append(c.hooks.TeamDefinition, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `teamdefinition.Intercept(f(g(h())))`.
func (c *TeamDefinitionClient) Intercept(interceptors ...Interceptor) {
	c.inters.TeamDefinition = append(c.inters.TeamDefinition, interceptors...)
}

// Create returns a builder for creating a TeamDefinition entity.
func (c *TeamDefinitionClient) Create() *TeamDefinitionCreate {
	mutation := newTeamDefinitionMutation(c.config, OpCreate)
	return &TeamDefinitionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TeamDefinition entities.
func (c *TeamDefinitionClient) CreateBulk(builders ...*TeamDefinitionCreate) *TeamDefinitionCreateBulk {
	return &TeamDefinitionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TeamDefinitionClient) MapCreateBulk(slice any, setFunc func(*TeamDefinitionCreate, int)) *TeamDefinitionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TeamDefinitionCreateBulk{err: fmt.Errorf("calling to TeamDefinitionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TeamDefinitionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TeamDefinitionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TeamDefinition.
func (c *TeamDefinitionClient) Update() *TeamDefinitionUpdate {
	mutation := newTeamDefinitionMutation(c.config, OpUpdate)
	return &TeamDefinitionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TeamDefinitionClient) UpdateOne(_m *TeamDefinition) *TeamDefinitionUpdateOne {
	mutation := newTeamDefinitionMutation(c.config, OpUpdateOne, withTeamDefinition(_m))
	return &TeamDefinitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TeamDefinitionClient) UpdateOneID(id uuid.UUID) *TeamDefinitionUpdateOne {
	mutation := newTeamDefinitionMutation(c.config, OpUpdateOne, withTeamDefinitionID(id))
	return &TeamDefinitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TeamDefinition.
func (c *TeamDefinitionClient) Delete() *TeamDefinitionDelete {
	mutation := newTeamDefinitionMutation(c.config, OpDelete)
	return &TeamDefinitionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TeamDefinitionClient) DeleteOne(_m *TeamDefinition) *TeamDefinitionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TeamDefinitionClient) DeleteOneID(id uuid.UUID) *TeamDefinitionDeleteOne {
	builder := c.Delete().Where(teamdefinition.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TeamDefinitionDeleteOne{builder}
}

// Query returns a query builder for TeamDefinition.
func (c *TeamDefinitionClient) Query() *TeamDefinitionQuery {
	return &TeamDefinitionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTeamDefinition},
		inters: c.Interceptors(),
	}
}

// Get returns a TeamDefinition entity by its id.
func (c *TeamDefinitionClient) Get(ctx context.Context, id uuid.UUID) (*TeamDefinition, error) {
	return c.Query().Where(teamdefinition.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TeamDefinitionClient) GetX(ctx context.Context, id uuid.UUID) *TeamDefinition {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAgents queries the agents edge of a TeamDefinition.
func (c *TeamDefinitionClient) QueryAgents(_m *TeamDefinition) *AgentDefinitionQuery {
	query := (&AgentDefinitionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(teamdefinition.Table, teamdefinition.FieldID, id),
			sqlgraph.To(agentdefinition.Table, agentdefinition.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, teamdefinition.AgentsTable, teamdefinition.AgentsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TeamDefinitionClient) Hooks() []Hook {
	return c.hooks.TeamDefinition
}

// Interceptors returns the client interceptors.
func (c *TeamDefinitionClient) Interceptors() []Interceptor {
	return c.inters.TeamDefinition
}

func (c *TeamDefinitionClient) mutate(ctx context.Context, m *TeamDefinitionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TeamDefinitionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TeamDefinitionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TeamDefinitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TeamDefinitionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TeamDefinition mutation op: %q", m.Op())
	}
}

// ViewClient is a client for the View schema.
type ViewClient struct {
	config
}

// NewViewClient returns a client for the View from the given config.
func NewViewClient(c config) *ViewClient {
	return &ViewClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `view.Hooks(f(g(h())))`.
func (c *ViewClient) Use(hooks ...Hook) {
	c.hooks.View = append(c.hooks.View, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `view.Intercept(f(g(h())))`.
func (c *ViewClient) Intercept(interceptors ...Interceptor) {
	c.inters.View = append(c.inters.View, interceptors...)
}

// Create returns a builder for creating a View entity.
func (c *ViewClient) Create() *ViewCreate {
	mutation := newViewMutation(c.config, OpCreate)
	return &ViewCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of View entities.
func (c *ViewClient) CreateBulk(builders ...*ViewCreate) *ViewCreateBulk {
	return &ViewCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ViewClient) MapCreateBulk(slice any, setFunc func(*ViewCreate, int)) *ViewCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ViewCreateBulk{err: fmt.Errorf("calling to ViewClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ViewCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ViewCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for View.
func (c *ViewClient) Update() *ViewUpdate {
	mutation := newViewMutation(c.config, OpUpdate)
	return &ViewUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ViewClient) UpdateOne(_m *View) *ViewUpdateOne {
	mutation := newViewMutation(c.config, OpUpdateOne, withView(_m))
	return &ViewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ViewClient) UpdateOneID(id uuid.UUID) *ViewUpdateOne {
	mutation := newViewMutation(c.config, OpUpdateOne, withViewID(id))
	return &ViewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for View.
func (c *ViewClient) Delete() *ViewDelete {
	mutation := newViewMutation(c.config, OpDelete)
	return &ViewDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ViewClient) DeleteOne(_m *View) *ViewDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ViewClient) DeleteOneID(id uuid.UUID) *ViewDeleteOne {
	builder := c.Delete().Where(view.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ViewDeleteOne{builder}
}

// Query returns a query builder for View.
func (c *ViewClient) Query() *ViewQuery {
	return &ViewQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeView},
		inters: c.Interceptors(),
	}
}

// Get returns a View entity by its id.
func (c *ViewClient) Get(ctx context.Context, id uuid.UUID) (*View, error) {
	return c.Query().Where(view.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ViewClient) GetX(ctx context.Context, id uuid.UUID) *View {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ViewClient) Hooks() []Hook {
	return c.hooks.View
}

// Interceptors returns the client interceptors.
func (c *ViewClient) Interceptors() []Interceptor {
	return c.inters.View
}

func (c *ViewClient) mutate(ctx context.Context, m *ViewMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ViewCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ViewUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ViewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ViewDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown View mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AgentDefinition, TeamDefinition, View []ent.Hook
	}
	inters struct {
		AgentDefinition, TeamDefinition, View []ent.Interceptor
	}
)
