// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/agentplexus/internal/ent/predicate"
	"github.com/plexusone/agentplexus/internal/ent/schema"
	"github.com/plexusone/agentplexus/internal/ent/view"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeView = "View"
)

// ViewMutation represents an operation that mutates the View nodes in the graph.
type ViewMutation struct {
	config
	op             Op
	typ            string
	id             *uuid.UUID
	name           *string
	teams          *[]string
	appendteams    []string
	node_positions *map[string]map[string]schema.Position
	left_width     *int
	addleft_width  *int
	right_width    *int
	addright_width *int
	created_at     *time.Time
	updated_at     *time.Time
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*View, error)
	predicates     []predicate.View
}

var _ ent.Mutation = (*ViewMutation)(nil)

// viewOption allows management of the mutation configuration using functional options.
type viewOption func(*ViewMutation)

// newViewMutation creates new mutation for the View entity.
func newViewMutation(c config, op Op, opts ...viewOption) *ViewMutation {
	m := &ViewMutation{
		config:        c,
		op:            op,
		typ:           TypeView,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withViewID sets the ID field of the mutation.
func withViewID(id uuid.UUID) viewOption {
	return func(m *ViewMutation) {
		var (
			err   error
			once  sync.Once
			value *View
		)
		m.oldValue = func(ctx context.Context) (*View, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().View.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withView sets the old View of the mutation.
func withView(node *View) viewOption {
	return func(m *ViewMutation) {
		m.oldValue = func(context.Context) (*View, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ViewMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ViewMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of View entities.
func (m *ViewMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ViewMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ViewMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().View.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ViewMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ViewMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the View entity.
// If the View object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ViewMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ViewMutation) ResetName() {
	m.name = nil
}

// SetTeams sets the "teams" field.
func (m *ViewMutation) SetTeams(s []string) {
	m.teams = &s
	m.appendteams = nil
}

// Teams returns the value of the "teams" field in the mutation.
func (m *ViewMutation) Teams() (r []string, exists bool) {
	v := m.teams
	if v == nil {
		return
	}
	return *v, true
}

// OldTeams returns the old "teams" field's value of the View entity.
// If the View object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ViewMutation) OldTeams(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTeams is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTeams requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTeams: %w", err)
	}
	return oldValue.Teams, nil
}

// AppendTeams adds s to the "teams" field.
func (m *ViewMutation) AppendTeams(s []string) {
	m.appendteams = append(m.appendteams, s...)
}

// AppendedTeams returns the list of values that were appended to the "teams" field in this mutation.
func (m *ViewMutation) AppendedTeams() ([]string, bool) {
	if len(m.appendteams) == 0 {
		return nil, false
	}
	return m.appendteams, true
}

// ResetTeams resets all changes to the "teams" field.
func (m *ViewMutation) ResetTeams() {
	m.teams = nil
	m.appendteams = nil
}

// SetNodePositions sets the "node_positions" field.
func (m *ViewMutation) SetNodePositions(value map[string]map[string]schema.Position) {
	m.node_positions = &value
}

// NodePositions returns the value of the "node_positions" field in the mutation.
func (m *ViewMutation) NodePositions() (r map[string]map[string]schema.Position, exists bool) {
	v := m.node_positions
	if v == nil {
		return
	}
	return *v, true
}

// OldNodePositions returns the old "node_positions" field's value of the View entity.
// If the View object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ViewMutation) OldNodePositions(ctx context.Context) (v map[string]map[string]schema.Position, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNodePositions is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNodePositions requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNodePositions: %w", err)
	}
	return oldValue.NodePositions, nil
}

// ResetNodePositions resets all changes to the "node_positions" field.
func (m *ViewMutation) ResetNodePositions() {
	m.node_positions = nil
}

// SetLeftWidth sets the "left_width" field.
func (m *ViewMutation) SetLeftWidth(i int) {
	m.left_width = &i
	m.addleft_width = nil
}

// LeftWidth returns the value of the "left_width" field in the mutation.
func (m *ViewMutation) LeftWidth() (r int, exists bool) {
	v := m.left_width
	if v == nil {
		return
	}
	return *v, true
}

// OldLeftWidth returns the old "left_width" field's value of the View entity.
// If the View object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ViewMutation) OldLeftWidth(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLeftWidth is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLeftWidth requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLeftWidth: %w", err)
	}
	return oldValue.LeftWidth, nil
}

// AddLeftWidth adds i to the "left_width" field.
func (m *ViewMutation) AddLeftWidth(i int) {
	if m.addleft_width != nil {
		*m.addleft_width += i
	} else {
		m.addleft_width = &i
	}
}

// AddedLeftWidth returns the value that was added to the "left_width" field in this mutation.
func (m *ViewMutation) AddedLeftWidth() (r int, exists bool) {
	v := m.addleft_width
	if v == nil {
		return
	}
	return *v, true
}

// ResetLeftWidth resets all changes to the "left_width" field.
func (m *ViewMutation) ResetLeftWidth() {
	m.left_width = nil
	m.addleft_width = nil
}

// SetRightWidth sets the "right_width" field.
func (m *ViewMutation) SetRightWidth(i int) {
	m.right_width = &i
	m.addright_width = nil
}

// RightWidth returns the value of the "right_width" field in the mutation.
func (m *ViewMutation) RightWidth() (r int, exists bool) {
	v := m.right_width
	if v == nil {
		return
	}
	return *v, true
}

// OldRightWidth returns the old "right_width" field's value of the View entity.
// If the View object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ViewMutation) OldRightWidth(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRightWidth is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRightWidth requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRightWidth: %w", err)
	}
	return oldValue.RightWidth, nil
}

// AddRightWidth adds i to the "right_width" field.
func (m *ViewMutation) AddRightWidth(i int) {
	if m.addright_width != nil {
		*m.addright_width += i
	} else {
		m.addright_width = &i
	}
}

// AddedRightWidth returns the value that was added to the "right_width" field in this mutation.
func (m *ViewMutation) AddedRightWidth() (r int, exists bool) {
	v := m.addright_width
	if v == nil {
		return
	}
	return *v, true
}

// ResetRightWidth resets all changes to the "right_width" field.
func (m *ViewMutation) ResetRightWidth() {
	m.right_width = nil
	m.addright_width = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *ViewMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ViewMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the View entity.
// If the View object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ViewMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ViewMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ViewMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ViewMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the View entity.
// If the View object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ViewMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ViewMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the ViewMutation builder.
func (m *ViewMutation) Where(ps ...predicate.View) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ViewMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ViewMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.View, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ViewMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ViewMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (View).
func (m *ViewMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ViewMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.name != nil {
		fields = append(fields, view.FieldName)
	}
	if m.teams != nil {
		fields = append(fields, view.FieldTeams)
	}
	if m.node_positions != nil {
		fields = append(fields, view.FieldNodePositions)
	}
	if m.left_width != nil {
		fields = append(fields, view.FieldLeftWidth)
	}
	if m.right_width != nil {
		fields = append(fields, view.FieldRightWidth)
	}
	if m.created_at != nil {
		fields = append(fields, view.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, view.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ViewMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case view.FieldName:
		return m.Name()
	case view.FieldTeams:
		return m.Teams()
	case view.FieldNodePositions:
		return m.NodePositions()
	case view.FieldLeftWidth:
		return m.LeftWidth()
	case view.FieldRightWidth:
		return m.RightWidth()
	case view.FieldCreatedAt:
		return m.CreatedAt()
	case view.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ViewMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case view.FieldName:
		return m.OldName(ctx)
	case view.FieldTeams:
		return m.OldTeams(ctx)
	case view.FieldNodePositions:
		return m.OldNodePositions(ctx)
	case view.FieldLeftWidth:
		return m.OldLeftWidth(ctx)
	case view.FieldRightWidth:
		return m.OldRightWidth(ctx)
	case view.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case view.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown View field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ViewMutation) SetField(name string, value ent.Value) error {
	switch name {
	case view.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case view.FieldTeams:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTeams(v)
		return nil
	case view.FieldNodePositions:
		v, ok := value.(map[string]map[string]schema.Position)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNodePositions(v)
		return nil
	case view.FieldLeftWidth:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLeftWidth(v)
		return nil
	case view.FieldRightWidth:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRightWidth(v)
		return nil
	case view.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case view.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown View field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ViewMutation) AddedFields() []string {
	var fields []string
	if m.addleft_width != nil {
		fields = append(fields, view.FieldLeftWidth)
	}
	if m.addright_width != nil {
		fields = append(fields, view.FieldRightWidth)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ViewMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case view.FieldLeftWidth:
		return m.AddedLeftWidth()
	case view.FieldRightWidth:
		return m.AddedRightWidth()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ViewMutation) AddField(name string, value ent.Value) error {
	switch name {
	case view.FieldLeftWidth:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLeftWidth(v)
		return nil
	case view.FieldRightWidth:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRightWidth(v)
		return nil
	}
	return fmt.Errorf("unknown View numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ViewMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ViewMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ViewMutation) ClearField(name string) error {
	return fmt.Errorf("unknown View nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ViewMutation) ResetField(name string) error {
	switch name {
	case view.FieldName:
		m.ResetName()
		return nil
	case view.FieldTeams:
		m.ResetTeams()
		return nil
	case view.FieldNodePositions:
		m.ResetNodePositions()
		return nil
	case view.FieldLeftWidth:
		m.ResetLeftWidth()
		return nil
	case view.FieldRightWidth:
		m.ResetRightWidth()
		return nil
	case view.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case view.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown View field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ViewMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ViewMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ViewMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ViewMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ViewMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ViewMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ViewMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown View unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ViewMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown View edge %s", name)
}
