// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/plexusone/agentplexus/internal/ent/schema"
	"github.com/plexusone/agentplexus/internal/ent/view"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	viewFields := schema.View{}.Fields()
	_ = viewFields
	// viewDescName is the schema descriptor for name field.
	viewDescName := viewFields[1].Descriptor()
	// view.NameValidator is a validator for the "name" field. It is called by the builders before save.
	view.NameValidator = viewDescName.Validators[0].(func(string) error)
	// viewDescLeftWidth is the schema descriptor for left_width field.
	viewDescLeftWidth := viewFields[4].Descriptor()
	// view.DefaultLeftWidth holds the default value on creation for the left_width field.
	view.DefaultLeftWidth = viewDescLeftWidth.Default.(int)
	// viewDescRightWidth is the schema descriptor for right_width field.
	viewDescRightWidth := viewFields[5].Descriptor()
	// view.DefaultRightWidth holds the default value on creation for the right_width field.
	view.DefaultRightWidth = viewDescRightWidth.Default.(int)
	// viewDescCreatedAt is the schema descriptor for created_at field.
	viewDescCreatedAt := viewFields[6].Descriptor()
	// view.DefaultCreatedAt holds the default value on creation for the created_at field.
	view.DefaultCreatedAt = viewDescCreatedAt.Default.(func() time.Time)
	// viewDescUpdatedAt is the schema descriptor for updated_at field.
	viewDescUpdatedAt := viewFields[7].Descriptor()
	// view.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	view.DefaultUpdatedAt = viewDescUpdatedAt.Default.(func() time.Time)
	// view.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	view.UpdateDefaultUpdatedAt = viewDescUpdatedAt.UpdateDefault.(func() time.Time)
	// viewDescID is the schema descriptor for id field.
	viewDescID := viewFields[0].Descriptor()
	// view.DefaultID holds the default value on creation for the id field.
	view.DefaultID = viewDescID.Default.(func() uuid.UUID)
}
