// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/agentplexus/internal/ent/teamdefinition"
)

// TeamDefinition is the model entity for the TeamDefinition schema.
type TeamDefinition struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Owning repository, e.g. agent-team-release
	RepoName string `json:"repo_name,omitempty"`
	// Team name from spec
	Name string `json:"name,omitempty"`
	// User-facing Go-style source path, e.g. github.com/plexusone/agent-team-release/teams/release
	SourceRef string `json:"source_ref,omitempty"`
	// Internal registry identity, xrn:agentplexus:team-definition:<id>
	RegistryXrn string `json:"registry_xrn,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Agent name that orchestrates this team's workflow
	Orchestrator string `json:"orchestrator,omitempty"`
	// Agent names referenced by the team spec, in spec order
	AgentNames []string `json:"agent_names,omitempty"`
	// Absolute path to the team JSON file
	SourcePath string `json:"source_path,omitempty"`
	// sha256 of the source file, for drift detection
	ContentHash string `json:"content_hash,omitempty"`
	// FirstSeenAt holds the value of the "first_seen_at" field.
	FirstSeenAt time.Time `json:"first_seen_at,omitempty"`
	// Updated on every successful registration sync
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamDefinitionQuery when eager-loading is set.
	Edges        TeamDefinitionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamDefinitionEdges holds the relations/edges for other nodes in the graph.
type TeamDefinitionEdges struct {
	// Agents holds the value of the agents edge.
	Agents []*AgentDefinition `json:"agents,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AgentsOrErr returns the Agents value or an error if the edge
// was not loaded in eager-loading.
func (e TeamDefinitionEdges) AgentsOrErr() ([]*AgentDefinition, error) {
	if e.loadedTypes[0] {
		return e.Agents, nil
	}
	return nil, &NotLoadedError{edge: "agents"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamDefinition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teamdefinition.FieldAgentNames:
			values[i] = new([]byte)
		case teamdefinition.FieldRepoName, teamdefinition.FieldName, teamdefinition.FieldSourceRef, teamdefinition.FieldRegistryXrn, teamdefinition.FieldVersion, teamdefinition.FieldDescription, teamdefinition.FieldOrchestrator, teamdefinition.FieldSourcePath, teamdefinition.FieldContentHash:
			values[i] = new(sql.NullString)
		case teamdefinition.FieldFirstSeenAt, teamdefinition.FieldLastSeenAt, teamdefinition.FieldCreatedAt, teamdefinition.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case teamdefinition.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamDefinition fields.
func (_m *TeamDefinition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teamdefinition.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case teamdefinition.FieldRepoName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_name", values[i])
			} else if value.Valid {
				_m.RepoName = value.String
			}
		case teamdefinition.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case teamdefinition.FieldSourceRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_ref", values[i])
			} else if value.Valid {
				_m.SourceRef = value.String
			}
		case teamdefinition.FieldRegistryXrn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field registry_xrn", values[i])
			} else if value.Valid {
				_m.RegistryXrn = value.String
			}
		case teamdefinition.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case teamdefinition.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case teamdefinition.FieldOrchestrator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field orchestrator", values[i])
			} else if value.Valid {
				_m.Orchestrator = value.String
			}
		case teamdefinition.FieldAgentNames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field agent_names", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AgentNames); err != nil {
					return fmt.Errorf("unmarshal field agent_names: %w", err)
				}
			}
		case teamdefinition.FieldSourcePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_path", values[i])
			} else if value.Valid {
				_m.SourcePath = value.String
			}
		case teamdefinition.FieldContentHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_hash", values[i])
			} else if value.Valid {
				_m.ContentHash = value.String
			}
		case teamdefinition.FieldFirstSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_seen_at", values[i])
			} else if value.Valid {
				_m.FirstSeenAt = value.Time
			}
		case teamdefinition.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case teamdefinition.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case teamdefinition.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamDefinition.
// This includes values selected through modifiers, order, etc.
func (_m *TeamDefinition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAgents queries the "agents" edge of the TeamDefinition entity.
func (_m *TeamDefinition) QueryAgents() *AgentDefinitionQuery {
	return NewTeamDefinitionClient(_m.config).QueryAgents(_m)
}

// Update returns a builder for updating this TeamDefinition.
// Note that you need to call TeamDefinition.Unwrap() before calling this method if this TeamDefinition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamDefinition) Update() *TeamDefinitionUpdateOne {
	return NewTeamDefinitionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamDefinition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamDefinition) Unwrap() *TeamDefinition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TeamDefinition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamDefinition) String() string {
	var builder strings.Builder
	builder.WriteString("TeamDefinition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("repo_name=")
	builder.WriteString(_m.RepoName)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("source_ref=")
	builder.WriteString(_m.SourceRef)
	builder.WriteString(", ")
	builder.WriteString("registry_xrn=")
	builder.WriteString(_m.RegistryXrn)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("orchestrator=")
	builder.WriteString(_m.Orchestrator)
	builder.WriteString(", ")
	builder.WriteString("agent_names=")
	builder.WriteString(fmt.Sprintf("%v", _m.AgentNames))
	builder.WriteString(", ")
	builder.WriteString("source_path=")
	builder.WriteString(_m.SourcePath)
	builder.WriteString(", ")
	builder.WriteString("content_hash=")
	builder.WriteString(_m.ContentHash)
	builder.WriteString(", ")
	builder.WriteString("first_seen_at=")
	builder.WriteString(_m.FirstSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TeamDefinitions is a parsable slice of TeamDefinition.
type TeamDefinitions []*TeamDefinition
