// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/agentplexus/internal/ent/predicate"
	"github.com/plexusone/agentplexus/internal/ent/teamdefinition"
)

// TeamDefinitionDelete is the builder for deleting a TeamDefinition entity.
type TeamDefinitionDelete struct {
	config
	hooks    []Hook
	mutation *TeamDefinitionMutation
}

// Where appends a list predicates to the TeamDefinitionDelete builder.
func (_d *TeamDefinitionDelete) Where(ps ...predicate.TeamDefinition) *TeamDefinitionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TeamDefinitionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamDefinitionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TeamDefinitionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(teamdefinition.Table, sqlgraph.NewFieldSpec(teamdefinition.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TeamDefinitionDeleteOne is the builder for deleting a single TeamDefinition entity.
type TeamDefinitionDeleteOne struct {
	_d *TeamDefinitionDelete
}

// Where appends a list predicates to the TeamDefinitionDelete builder.
func (_d *TeamDefinitionDeleteOne) Where(ps ...predicate.TeamDefinition) *TeamDefinitionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TeamDefinitionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{teamdefinition.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamDefinitionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
