// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/agentplexus/internal/ent/agentdefinition"
	"github.com/plexusone/agentplexus/internal/ent/teamdefinition"
)

// TeamDefinitionCreate is the builder for creating a TeamDefinition entity.
type TeamDefinitionCreate struct {
	config
	mutation *TeamDefinitionMutation
	hooks    []Hook
}

// SetRepoName sets the "repo_name" field.
func (_c *TeamDefinitionCreate) SetRepoName(v string) *TeamDefinitionCreate {
	_c.mutation.SetRepoName(v)
	return _c
}

// SetName sets the "name" field.
func (_c *TeamDefinitionCreate) SetName(v string) *TeamDefinitionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSourceRef sets the "source_ref" field.
func (_c *TeamDefinitionCreate) SetSourceRef(v string) *TeamDefinitionCreate {
	_c.mutation.SetSourceRef(v)
	return _c
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_c *TeamDefinitionCreate) SetNillableSourceRef(v *string) *TeamDefinitionCreate {
	if v != nil {
		_c.SetSourceRef(*v)
	}
	return _c
}

// SetRegistryXrn sets the "registry_xrn" field.
func (_c *TeamDefinitionCreate) SetRegistryXrn(v string) *TeamDefinitionCreate {
	_c.mutation.SetRegistryXrn(v)
	return _c
}

// SetNillableRegistryXrn sets the "registry_xrn" field if the given value is not nil.
func (_c *TeamDefinitionCreate) SetNillableRegistryXrn(v *string) *TeamDefinitionCreate {
	if v != nil {
		_c.SetRegistryXrn(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *TeamDefinitionCreate) SetVersion(v string) *TeamDefinitionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *TeamDefinitionCreate) SetNillableVersion(v *string) *TeamDefinitionCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *TeamDefinitionCreate) SetDescription(v string) *TeamDefinitionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TeamDefinitionCreate) SetNillableDescription(v *string) *TeamDefinitionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetOrchestrator sets the "orchestrator" field.
func (_c *TeamDefinitionCreate) SetOrchestrator(v string) *TeamDefinitionCreate {
	_c.mutation.SetOrchestrator(v)
	return _c
}

// SetNillableOrchestrator sets the "orchestrator" field if the given value is not nil.
func (_c *TeamDefinitionCreate) SetNillableOrchestrator(v *string) *TeamDefinitionCreate {
	if v != nil {
		_c.SetOrchestrator(*v)
	}
	return _c
}

// SetAgentNames sets the "agent_names" field.
func (_c *TeamDefinitionCreate) SetAgentNames(v []string) *TeamDefinitionCreate {
	_c.mutation.SetAgentNames(v)
	return _c
}

// SetSourcePath sets the "source_path" field.
func (_c *TeamDefinitionCreate) SetSourcePath(v string) *TeamDefinitionCreate {
	_c.mutation.SetSourcePath(v)
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *TeamDefinitionCreate) SetContentHash(v string) *TeamDefinitionCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_c *TeamDefinitionCreate) SetFirstSeenAt(v time.Time) *TeamDefinitionCreate {
	_c.mutation.SetFirstSeenAt(v)
	return _c
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_c *TeamDefinitionCreate) SetNillableFirstSeenAt(v *time.Time) *TeamDefinitionCreate {
	if v != nil {
		_c.SetFirstSeenAt(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *TeamDefinitionCreate) SetLastSeenAt(v time.Time) *TeamDefinitionCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *TeamDefinitionCreate) SetNillableLastSeenAt(v *time.Time) *TeamDefinitionCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamDefinitionCreate) SetCreatedAt(v time.Time) *TeamDefinitionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamDefinitionCreate) SetNillableCreatedAt(v *time.Time) *TeamDefinitionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TeamDefinitionCreate) SetUpdatedAt(v time.Time) *TeamDefinitionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TeamDefinitionCreate) SetNillableUpdatedAt(v *time.Time) *TeamDefinitionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TeamDefinitionCreate) SetID(v uuid.UUID) *TeamDefinitionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TeamDefinitionCreate) SetNillableID(v *uuid.UUID) *TeamDefinitionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddAgentIDs adds the "agents" edge to the AgentDefinition entity by IDs.
func (_c *TeamDefinitionCreate) AddAgentIDs(ids ...uuid.UUID) *TeamDefinitionCreate {
	_c.mutation.AddAgentIDs(ids...)
	return _c
}

// AddAgents adds the "agents" edges to the AgentDefinition entity.
func (_c *TeamDefinitionCreate) AddAgents(v ...*AgentDefinition) *TeamDefinitionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAgentIDs(ids...)
}

// Mutation returns the TeamDefinitionMutation object of the builder.
func (_c *TeamDefinitionCreate) Mutation() *TeamDefinitionMutation {
	return _c.mutation
}

// Save creates the TeamDefinition in the database.
func (_c *TeamDefinitionCreate) Save(ctx context.Context) (*TeamDefinition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamDefinitionCreate) SaveX(ctx context.Context) *TeamDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamDefinitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamDefinitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamDefinitionCreate) defaults() {
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		v := teamdefinition.DefaultFirstSeenAt()
		_c.mutation.SetFirstSeenAt(v)
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := teamdefinition.DefaultLastSeenAt()
		_c.mutation.SetLastSeenAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teamdefinition.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := teamdefinition.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := teamdefinition.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamDefinitionCreate) check() error {
	if _, ok := _c.mutation.RepoName(); !ok {
		return &ValidationError{Name: "repo_name", err: errors.New(`ent: missing required field "TeamDefinition.repo_name"`)}
	}
	if v, ok := _c.mutation.RepoName(); ok {
		if err := teamdefinition.RepoNameValidator(v); err != nil {
			return &ValidationError{Name: "repo_name", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.repo_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TeamDefinition.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := teamdefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourcePath(); !ok {
		return &ValidationError{Name: "source_path", err: errors.New(`ent: missing required field "TeamDefinition.source_path"`)}
	}
	if v, ok := _c.mutation.SourcePath(); ok {
		if err := teamdefinition.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.source_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentHash(); !ok {
		return &ValidationError{Name: "content_hash", err: errors.New(`ent: missing required field "TeamDefinition.content_hash"`)}
	}
	if v, ok := _c.mutation.ContentHash(); ok {
		if err := teamdefinition.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.content_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		return &ValidationError{Name: "first_seen_at", err: errors.New(`ent: missing required field "TeamDefinition.first_seen_at"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "TeamDefinition.last_seen_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamDefinition.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TeamDefinition.updated_at"`)}
	}
	return nil
}

func (_c *TeamDefinitionCreate) sqlSave(ctx context.Context) (*TeamDefinition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamDefinitionCreate) createSpec() (*TeamDefinition, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamDefinition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teamdefinition.Table, sqlgraph.NewFieldSpec(teamdefinition.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RepoName(); ok {
		_spec.SetField(teamdefinition.FieldRepoName, field.TypeString, value)
		_node.RepoName = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(teamdefinition.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SourceRef(); ok {
		_spec.SetField(teamdefinition.FieldSourceRef, field.TypeString, value)
		_node.SourceRef = value
	}
	if value, ok := _c.mutation.RegistryXrn(); ok {
		_spec.SetField(teamdefinition.FieldRegistryXrn, field.TypeString, value)
		_node.RegistryXrn = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(teamdefinition.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(teamdefinition.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Orchestrator(); ok {
		_spec.SetField(teamdefinition.FieldOrchestrator, field.TypeString, value)
		_node.Orchestrator = value
	}
	if value, ok := _c.mutation.AgentNames(); ok {
		_spec.SetField(teamdefinition.FieldAgentNames, field.TypeJSON, value)
		_node.AgentNames = value
	}
	if value, ok := _c.mutation.SourcePath(); ok {
		_spec.SetField(teamdefinition.FieldSourcePath, field.TypeString, value)
		_node.SourcePath = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(teamdefinition.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.FirstSeenAt(); ok {
		_spec.SetField(teamdefinition.FieldFirstSeenAt, field.TypeTime, value)
		_node.FirstSeenAt = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(teamdefinition.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teamdefinition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(teamdefinition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teamdefinition.AgentsTable,
			Columns: teamdefinition.AgentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TeamDefinitionCreateBulk is the builder for creating many TeamDefinition entities in bulk.
type TeamDefinitionCreateBulk struct {
	config
	err      error
	builders []*TeamDefinitionCreate
}

// Save creates the TeamDefinition entities in the database.
func (_c *TeamDefinitionCreateBulk) Save(ctx context.Context) ([]*TeamDefinition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamDefinition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamDefinitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamDefinitionCreateBulk) SaveX(ctx context.Context) []*TeamDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamDefinitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamDefinitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
