// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/agentplexus/internal/ent/agentdefinition"
	"github.com/plexusone/agentplexus/internal/ent/predicate"
	"github.com/plexusone/agentplexus/internal/ent/teamdefinition"
)

// TeamDefinitionUpdate is the builder for updating TeamDefinition entities.
type TeamDefinitionUpdate struct {
	config
	hooks    []Hook
	mutation *TeamDefinitionMutation
}

// Where appends a list predicates to the TeamDefinitionUpdate builder.
func (_u *TeamDefinitionUpdate) Where(ps ...predicate.TeamDefinition) *TeamDefinitionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRepoName sets the "repo_name" field.
func (_u *TeamDefinitionUpdate) SetRepoName(v string) *TeamDefinitionUpdate {
	_u.mutation.SetRepoName(v)
	return _u
}

// SetNillableRepoName sets the "repo_name" field if the given value is not nil.
func (_u *TeamDefinitionUpdate) SetNillableRepoName(v *string) *TeamDefinitionUpdate {
	if v != nil {
		_u.SetRepoName(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TeamDefinitionUpdate) SetName(v string) *TeamDefinitionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamDefinitionUpdate) SetNillableName(v *string) *TeamDefinitionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *TeamDefinitionUpdate) SetSourceRef(v string) *TeamDefinitionUpdate {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *TeamDefinitionUpdate) SetNillableSourceRef(v *string) *TeamDefinitionUpdate {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (_u *TeamDefinitionUpdate) ClearSourceRef() *TeamDefinitionUpdate {
	_u.mutation.ClearSourceRef()
	return _u
}

// SetVersion sets the "version" field.
func (_u *TeamDefinitionUpdate) SetVersion(v string) *TeamDefinitionUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TeamDefinitionUpdate) SetNillableVersion(v *string) *TeamDefinitionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *TeamDefinitionUpdate) ClearVersion() *TeamDefinitionUpdate {
	_u.mutation.ClearVersion()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TeamDefinitionUpdate) SetDescription(v string) *TeamDefinitionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TeamDefinitionUpdate) SetNillableDescription(v *string) *TeamDefinitionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TeamDefinitionUpdate) ClearDescription() *TeamDefinitionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetOrchestrator sets the "orchestrator" field.
func (_u *TeamDefinitionUpdate) SetOrchestrator(v string) *TeamDefinitionUpdate {
	_u.mutation.SetOrchestrator(v)
	return _u
}

// SetNillableOrchestrator sets the "orchestrator" field if the given value is not nil.
func (_u *TeamDefinitionUpdate) SetNillableOrchestrator(v *string) *TeamDefinitionUpdate {
	if v != nil {
		_u.SetOrchestrator(*v)
	}
	return _u
}

// ClearOrchestrator clears the value of the "orchestrator" field.
func (_u *TeamDefinitionUpdate) ClearOrchestrator() *TeamDefinitionUpdate {
	_u.mutation.ClearOrchestrator()
	return _u
}

// SetAgentNames sets the "agent_names" field.
func (_u *TeamDefinitionUpdate) SetAgentNames(v []string) *TeamDefinitionUpdate {
	_u.mutation.SetAgentNames(v)
	return _u
}

// AppendAgentNames appends value to the "agent_names" field.
func (_u *TeamDefinitionUpdate) AppendAgentNames(v []string) *TeamDefinitionUpdate {
	_u.mutation.AppendAgentNames(v)
	return _u
}

// ClearAgentNames clears the value of the "agent_names" field.
func (_u *TeamDefinitionUpdate) ClearAgentNames() *TeamDefinitionUpdate {
	_u.mutation.ClearAgentNames()
	return _u
}

// SetSourcePath sets the "source_path" field.
func (_u *TeamDefinitionUpdate) SetSourcePath(v string) *TeamDefinitionUpdate {
	_u.mutation.SetSourcePath(v)
	return _u
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (_u *TeamDefinitionUpdate) SetNillableSourcePath(v *string) *TeamDefinitionUpdate {
	if v != nil {
		_u.SetSourcePath(*v)
	}
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *TeamDefinitionUpdate) SetContentHash(v string) *TeamDefinitionUpdate {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *TeamDefinitionUpdate) SetNillableContentHash(v *string) *TeamDefinitionUpdate {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *TeamDefinitionUpdate) SetLastSeenAt(v time.Time) *TeamDefinitionUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *TeamDefinitionUpdate) SetNillableLastSeenAt(v *time.Time) *TeamDefinitionUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamDefinitionUpdate) SetUpdatedAt(v time.Time) *TeamDefinitionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAgentIDs adds the "agents" edge to the AgentDefinition entity by IDs.
func (_u *TeamDefinitionUpdate) AddAgentIDs(ids ...uuid.UUID) *TeamDefinitionUpdate {
	_u.mutation.AddAgentIDs(ids...)
	return _u
}

// AddAgents adds the "agents" edges to the AgentDefinition entity.
func (_u *TeamDefinitionUpdate) AddAgents(v ...*AgentDefinition) *TeamDefinitionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgentIDs(ids...)
}

// Mutation returns the TeamDefinitionMutation object of the builder.
func (_u *TeamDefinitionUpdate) Mutation() *TeamDefinitionMutation {
	return _u.mutation
}

// ClearAgents clears all "agents" edges to the AgentDefinition entity.
func (_u *TeamDefinitionUpdate) ClearAgents() *TeamDefinitionUpdate {
	_u.mutation.ClearAgents()
	return _u
}

// RemoveAgentIDs removes the "agents" edge to AgentDefinition entities by IDs.
func (_u *TeamDefinitionUpdate) RemoveAgentIDs(ids ...uuid.UUID) *TeamDefinitionUpdate {
	_u.mutation.RemoveAgentIDs(ids...)
	return _u
}

// RemoveAgents removes "agents" edges to AgentDefinition entities.
func (_u *TeamDefinitionUpdate) RemoveAgents(v ...*AgentDefinition) *TeamDefinitionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamDefinitionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamDefinitionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamDefinitionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamDefinitionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamDefinitionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teamdefinition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamDefinitionUpdate) check() error {
	if v, ok := _u.mutation.RepoName(); ok {
		if err := teamdefinition.RepoNameValidator(v); err != nil {
			return &ValidationError{Name: "repo_name", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.repo_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := teamdefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourcePath(); ok {
		if err := teamdefinition.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.source_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := teamdefinition.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.content_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamDefinitionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamdefinition.Table, teamdefinition.Columns, sqlgraph.NewFieldSpec(teamdefinition.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoName(); ok {
		_spec.SetField(teamdefinition.FieldRepoName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(teamdefinition.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(teamdefinition.FieldSourceRef, field.TypeString, value)
	}
	if _u.mutation.SourceRefCleared() {
		_spec.ClearField(teamdefinition.FieldSourceRef, field.TypeString)
	}
	if _u.mutation.RegistryXrnCleared() {
		_spec.ClearField(teamdefinition.FieldRegistryXrn, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(teamdefinition.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(teamdefinition.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(teamdefinition.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(teamdefinition.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Orchestrator(); ok {
		_spec.SetField(teamdefinition.FieldOrchestrator, field.TypeString, value)
	}
	if _u.mutation.OrchestratorCleared() {
		_spec.ClearField(teamdefinition.FieldOrchestrator, field.TypeString)
	}
	if value, ok := _u.mutation.AgentNames(); ok {
		_spec.SetField(teamdefinition.FieldAgentNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAgentNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, teamdefinition.FieldAgentNames, value)
		})
	}
	if _u.mutation.AgentNamesCleared() {
		_spec.ClearField(teamdefinition.FieldAgentNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.SourcePath(); ok {
		_spec.SetField(teamdefinition.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(teamdefinition.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(teamdefinition.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamdefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teamdefinition.AgentsTable,
			Columns: teamdefinition.AgentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgentsIDs(); len(nodes) > 0 && !_u.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teamdefinition.AgentsTable,
			Columns: teamdefinition.AgentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teamdefinition.AgentsTable,
			Columns: teamdefinition.AgentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamdefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamDefinitionUpdateOne is the builder for updating a single TeamDefinition entity.
type TeamDefinitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamDefinitionMutation
}

// SetRepoName sets the "repo_name" field.
func (_u *TeamDefinitionUpdateOne) SetRepoName(v string) *TeamDefinitionUpdateOne {
	_u.mutation.SetRepoName(v)
	return _u
}

// SetNillableRepoName sets the "repo_name" field if the given value is not nil.
func (_u *TeamDefinitionUpdateOne) SetNillableRepoName(v *string) *TeamDefinitionUpdateOne {
	if v != nil {
		_u.SetRepoName(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TeamDefinitionUpdateOne) SetName(v string) *TeamDefinitionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamDefinitionUpdateOne) SetNillableName(v *string) *TeamDefinitionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *TeamDefinitionUpdateOne) SetSourceRef(v string) *TeamDefinitionUpdateOne {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *TeamDefinitionUpdateOne) SetNillableSourceRef(v *string) *TeamDefinitionUpdateOne {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (_u *TeamDefinitionUpdateOne) ClearSourceRef() *TeamDefinitionUpdateOne {
	_u.mutation.ClearSourceRef()
	return _u
}

// SetVersion sets the "version" field.
func (_u *TeamDefinitionUpdateOne) SetVersion(v string) *TeamDefinitionUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TeamDefinitionUpdateOne) SetNillableVersion(v *string) *TeamDefinitionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *TeamDefinitionUpdateOne) ClearVersion() *TeamDefinitionUpdateOne {
	_u.mutation.ClearVersion()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TeamDefinitionUpdateOne) SetDescription(v string) *TeamDefinitionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TeamDefinitionUpdateOne) SetNillableDescription(v *string) *TeamDefinitionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TeamDefinitionUpdateOne) ClearDescription() *TeamDefinitionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetOrchestrator sets the "orchestrator" field.
func (_u *TeamDefinitionUpdateOne) SetOrchestrator(v string) *TeamDefinitionUpdateOne {
	_u.mutation.SetOrchestrator(v)
	return _u
}

// SetNillableOrchestrator sets the "orchestrator" field if the given value is not nil.
func (_u *TeamDefinitionUpdateOne) SetNillableOrchestrator(v *string) *TeamDefinitionUpdateOne {
	if v != nil {
		_u.SetOrchestrator(*v)
	}
	return _u
}

// ClearOrchestrator clears the value of the "orchestrator" field.
func (_u *TeamDefinitionUpdateOne) ClearOrchestrator() *TeamDefinitionUpdateOne {
	_u.mutation.ClearOrchestrator()
	return _u
}

// SetAgentNames sets the "agent_names" field.
func (_u *TeamDefinitionUpdateOne) SetAgentNames(v []string) *TeamDefinitionUpdateOne {
	_u.mutation.SetAgentNames(v)
	return _u
}

// AppendAgentNames appends value to the "agent_names" field.
func (_u *TeamDefinitionUpdateOne) AppendAgentNames(v []string) *TeamDefinitionUpdateOne {
	_u.mutation.AppendAgentNames(v)
	return _u
}

// ClearAgentNames clears the value of the "agent_names" field.
func (_u *TeamDefinitionUpdateOne) ClearAgentNames() *TeamDefinitionUpdateOne {
	_u.mutation.ClearAgentNames()
	return _u
}

// SetSourcePath sets the "source_path" field.
func (_u *TeamDefinitionUpdateOne) SetSourcePath(v string) *TeamDefinitionUpdateOne {
	_u.mutation.SetSourcePath(v)
	return _u
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (_u *TeamDefinitionUpdateOne) SetNillableSourcePath(v *string) *TeamDefinitionUpdateOne {
	if v != nil {
		_u.SetSourcePath(*v)
	}
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *TeamDefinitionUpdateOne) SetContentHash(v string) *TeamDefinitionUpdateOne {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *TeamDefinitionUpdateOne) SetNillableContentHash(v *string) *TeamDefinitionUpdateOne {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *TeamDefinitionUpdateOne) SetLastSeenAt(v time.Time) *TeamDefinitionUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *TeamDefinitionUpdateOne) SetNillableLastSeenAt(v *time.Time) *TeamDefinitionUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamDefinitionUpdateOne) SetUpdatedAt(v time.Time) *TeamDefinitionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAgentIDs adds the "agents" edge to the AgentDefinition entity by IDs.
func (_u *TeamDefinitionUpdateOne) AddAgentIDs(ids ...uuid.UUID) *TeamDefinitionUpdateOne {
	_u.mutation.AddAgentIDs(ids...)
	return _u
}

// AddAgents adds the "agents" edges to the AgentDefinition entity.
func (_u *TeamDefinitionUpdateOne) AddAgents(v ...*AgentDefinition) *TeamDefinitionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgentIDs(ids...)
}

// Mutation returns the TeamDefinitionMutation object of the builder.
func (_u *TeamDefinitionUpdateOne) Mutation() *TeamDefinitionMutation {
	return _u.mutation
}

// ClearAgents clears all "agents" edges to the AgentDefinition entity.
func (_u *TeamDefinitionUpdateOne) ClearAgents() *TeamDefinitionUpdateOne {
	_u.mutation.ClearAgents()
	return _u
}

// RemoveAgentIDs removes the "agents" edge to AgentDefinition entities by IDs.
func (_u *TeamDefinitionUpdateOne) RemoveAgentIDs(ids ...uuid.UUID) *TeamDefinitionUpdateOne {
	_u.mutation.RemoveAgentIDs(ids...)
	return _u
}

// RemoveAgents removes "agents" edges to AgentDefinition entities.
func (_u *TeamDefinitionUpdateOne) RemoveAgents(v ...*AgentDefinition) *TeamDefinitionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgentIDs(ids...)
}

// Where appends a list predicates to the TeamDefinitionUpdate builder.
func (_u *TeamDefinitionUpdateOne) Where(ps ...predicate.TeamDefinition) *TeamDefinitionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamDefinitionUpdateOne) Select(field string, fields ...string) *TeamDefinitionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamDefinition entity.
func (_u *TeamDefinitionUpdateOne) Save(ctx context.Context) (*TeamDefinition, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamDefinitionUpdateOne) SaveX(ctx context.Context) *TeamDefinition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamDefinitionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamDefinitionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamDefinitionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teamdefinition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamDefinitionUpdateOne) check() error {
	if v, ok := _u.mutation.RepoName(); ok {
		if err := teamdefinition.RepoNameValidator(v); err != nil {
			return &ValidationError{Name: "repo_name", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.repo_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := teamdefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourcePath(); ok {
		if err := teamdefinition.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.source_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := teamdefinition.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "TeamDefinition.content_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamDefinitionUpdateOne) sqlSave(ctx context.Context) (_node *TeamDefinition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamdefinition.Table, teamdefinition.Columns, sqlgraph.NewFieldSpec(teamdefinition.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamDefinition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamdefinition.FieldID)
		for _, f := range fields {
			if !teamdefinition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamdefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoName(); ok {
		_spec.SetField(teamdefinition.FieldRepoName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(teamdefinition.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(teamdefinition.FieldSourceRef, field.TypeString, value)
	}
	if _u.mutation.SourceRefCleared() {
		_spec.ClearField(teamdefinition.FieldSourceRef, field.TypeString)
	}
	if _u.mutation.RegistryXrnCleared() {
		_spec.ClearField(teamdefinition.FieldRegistryXrn, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(teamdefinition.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(teamdefinition.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(teamdefinition.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(teamdefinition.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Orchestrator(); ok {
		_spec.SetField(teamdefinition.FieldOrchestrator, field.TypeString, value)
	}
	if _u.mutation.OrchestratorCleared() {
		_spec.ClearField(teamdefinition.FieldOrchestrator, field.TypeString)
	}
	if value, ok := _u.mutation.AgentNames(); ok {
		_spec.SetField(teamdefinition.FieldAgentNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAgentNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, teamdefinition.FieldAgentNames, value)
		})
	}
	if _u.mutation.AgentNamesCleared() {
		_spec.ClearField(teamdefinition.FieldAgentNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.SourcePath(); ok {
		_spec.SetField(teamdefinition.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(teamdefinition.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(teamdefinition.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamdefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teamdefinition.AgentsTable,
			Columns: teamdefinition.AgentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgentsIDs(); len(nodes) > 0 && !_u.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teamdefinition.AgentsTable,
			Columns: teamdefinition.AgentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teamdefinition.AgentsTable,
			Columns: teamdefinition.AgentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentdefinition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamDefinition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamdefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
