// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentplexus/multi-agent-designer/internal/ent/schema"
	"github.com/agentplexus/multi-agent-designer/internal/ent/view"
	"github.com/google/uuid"
)

// ViewCreate is the builder for creating a View entity.
type ViewCreate struct {
	config
	mutation *ViewMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ViewCreate) SetName(v string) *ViewCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTeams sets the "teams" field.
func (_c *ViewCreate) SetTeams(v []string) *ViewCreate {
	_c.mutation.SetTeams(v)
	return _c
}

// SetNodePositions sets the "node_positions" field.
func (_c *ViewCreate) SetNodePositions(v map[string]map[string]schema.Position) *ViewCreate {
	_c.mutation.SetNodePositions(v)
	return _c
}

// SetLeftWidth sets the "left_width" field.
func (_c *ViewCreate) SetLeftWidth(v int) *ViewCreate {
	_c.mutation.SetLeftWidth(v)
	return _c
}

// SetNillableLeftWidth sets the "left_width" field if the given value is not nil.
func (_c *ViewCreate) SetNillableLeftWidth(v *int) *ViewCreate {
	if v != nil {
		_c.SetLeftWidth(*v)
	}
	return _c
}

// SetRightWidth sets the "right_width" field.
func (_c *ViewCreate) SetRightWidth(v int) *ViewCreate {
	_c.mutation.SetRightWidth(v)
	return _c
}

// SetNillableRightWidth sets the "right_width" field if the given value is not nil.
func (_c *ViewCreate) SetNillableRightWidth(v *int) *ViewCreate {
	if v != nil {
		_c.SetRightWidth(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ViewCreate) SetCreatedAt(v time.Time) *ViewCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ViewCreate) SetNillableCreatedAt(v *time.Time) *ViewCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ViewCreate) SetUpdatedAt(v time.Time) *ViewCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ViewCreate) SetNillableUpdatedAt(v *time.Time) *ViewCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ViewCreate) SetID(v uuid.UUID) *ViewCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ViewCreate) SetNillableID(v *uuid.UUID) *ViewCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ViewMutation object of the builder.
func (_c *ViewCreate) Mutation() *ViewMutation {
	return _c.mutation
}

// Save creates the View in the database.
func (_c *ViewCreate) Save(ctx context.Context) (*View, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ViewCreate) SaveX(ctx context.Context) *View {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ViewCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ViewCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ViewCreate) defaults() {
	if _, ok := _c.mutation.LeftWidth(); !ok {
		v := view.DefaultLeftWidth
		_c.mutation.SetLeftWidth(v)
	}
	if _, ok := _c.mutation.RightWidth(); !ok {
		v := view.DefaultRightWidth
		_c.mutation.SetRightWidth(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := view.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := view.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := view.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ViewCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "View.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := view.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "View.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Teams(); !ok {
		return &ValidationError{Name: "teams", err: errors.New(`ent: missing required field "View.teams"`)}
	}
	if _, ok := _c.mutation.NodePositions(); !ok {
		return &ValidationError{Name: "node_positions", err: errors.New(`ent: missing required field "View.node_positions"`)}
	}
	if _, ok := _c.mutation.LeftWidth(); !ok {
		return &ValidationError{Name: "left_width", err: errors.New(`ent: missing required field "View.left_width"`)}
	}
	if _, ok := _c.mutation.RightWidth(); !ok {
		return &ValidationError{Name: "right_width", err: errors.New(`ent: missing required field "View.right_width"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "View.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "View.updated_at"`)}
	}
	return nil
}

func (_c *ViewCreate) sqlSave(ctx context.Context) (*View, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ViewCreate) createSpec() (*View, *sqlgraph.CreateSpec) {
	var (
		_node = &View{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(view.Table, sqlgraph.NewFieldSpec(view.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(view.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Teams(); ok {
		_spec.SetField(view.FieldTeams, field.TypeJSON, value)
		_node.Teams = value
	}
	if value, ok := _c.mutation.NodePositions(); ok {
		_spec.SetField(view.FieldNodePositions, field.TypeJSON, value)
		_node.NodePositions = value
	}
	if value, ok := _c.mutation.LeftWidth(); ok {
		_spec.SetField(view.FieldLeftWidth, field.TypeInt, value)
		_node.LeftWidth = value
	}
	if value, ok := _c.mutation.RightWidth(); ok {
		_spec.SetField(view.FieldRightWidth, field.TypeInt, value)
		_node.RightWidth = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(view.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(view.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ViewCreateBulk is the builder for creating many View entities in bulk.
type ViewCreateBulk struct {
	config
	err      error
	builders []*ViewCreate
}

// Save creates the View entities in the database.
func (_c *ViewCreateBulk) Save(ctx context.Context) ([]*View, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*View, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ViewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ViewCreateBulk) SaveX(ctx context.Context) []*View {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ViewCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ViewCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
