// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/agentplexus/multi-agent-designer/internal/ent/schema"
	"github.com/agentplexus/multi-agent-designer/internal/ent/view"
	"github.com/google/uuid"
)

// View is the model entity for the View schema.
type View struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Team names in display order
	Teams []string `json:"teams,omitempty"`
	// teamName -> nodeId -> position
	NodePositions map[string]map[string]schema.Position `json:"node_positions,omitempty"`
	// LeftWidth holds the value of the "left_width" field.
	LeftWidth int `json:"left_width,omitempty"`
	// RightWidth holds the value of the "right_width" field.
	RightWidth int `json:"right_width,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*View) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case view.FieldTeams, view.FieldNodePositions:
			values[i] = new([]byte)
		case view.FieldLeftWidth, view.FieldRightWidth:
			values[i] = new(sql.NullInt64)
		case view.FieldName:
			values[i] = new(sql.NullString)
		case view.FieldCreatedAt, view.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case view.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the View fields.
func (_m *View) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case view.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case view.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case view.FieldTeams:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field teams", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Teams); err != nil {
					return fmt.Errorf("unmarshal field teams: %w", err)
				}
			}
		case view.FieldNodePositions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field node_positions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NodePositions); err != nil {
					return fmt.Errorf("unmarshal field node_positions: %w", err)
				}
			}
		case view.FieldLeftWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field left_width", values[i])
			} else if value.Valid {
				_m.LeftWidth = int(value.Int64)
			}
		case view.FieldRightWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field right_width", values[i])
			} else if value.Valid {
				_m.RightWidth = int(value.Int64)
			}
		case view.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case view.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the View.
// This includes values selected through modifiers, order, etc.
func (_m *View) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this View.
// Note that you need to call View.Unwrap() before calling this method if this View
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *View) Update() *ViewUpdateOne {
	return NewViewClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the View entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *View) Unwrap() *View {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: View is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *View) String() string {
	var builder strings.Builder
	builder.WriteString("View(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("teams=")
	builder.WriteString(fmt.Sprintf("%v", _m.Teams))
	builder.WriteString(", ")
	builder.WriteString("node_positions=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodePositions))
	builder.WriteString(", ")
	builder.WriteString("left_width=")
	builder.WriteString(fmt.Sprintf("%v", _m.LeftWidth))
	builder.WriteString(", ")
	builder.WriteString("right_width=")
	builder.WriteString(fmt.Sprintf("%v", _m.RightWidth))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Views is a parsable slice of View.
type Views []*View
