// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/agentplexus/internal/ent/predicate"
	"github.com/plexusone/agentplexus/internal/ent/schema"
	"github.com/plexusone/agentplexus/internal/ent/view"
)

// ViewUpdate is the builder for updating View entities.
type ViewUpdate struct {
	config
	hooks    []Hook
	mutation *ViewMutation
}

// Where appends a list predicates to the ViewUpdate builder.
func (_u *ViewUpdate) Where(ps ...predicate.View) *ViewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ViewUpdate) SetName(v string) *ViewUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ViewUpdate) SetNillableName(v *string) *ViewUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTeams sets the "teams" field.
func (_u *ViewUpdate) SetTeams(v []string) *ViewUpdate {
	_u.mutation.SetTeams(v)
	return _u
}

// AppendTeams appends value to the "teams" field.
func (_u *ViewUpdate) AppendTeams(v []string) *ViewUpdate {
	_u.mutation.AppendTeams(v)
	return _u
}

// SetNodePositions sets the "node_positions" field.
func (_u *ViewUpdate) SetNodePositions(v map[string]map[string]schema.Position) *ViewUpdate {
	_u.mutation.SetNodePositions(v)
	return _u
}

// SetLeftWidth sets the "left_width" field.
func (_u *ViewUpdate) SetLeftWidth(v int) *ViewUpdate {
	_u.mutation.ResetLeftWidth()
	_u.mutation.SetLeftWidth(v)
	return _u
}

// SetNillableLeftWidth sets the "left_width" field if the given value is not nil.
func (_u *ViewUpdate) SetNillableLeftWidth(v *int) *ViewUpdate {
	if v != nil {
		_u.SetLeftWidth(*v)
	}
	return _u
}

// AddLeftWidth adds value to the "left_width" field.
func (_u *ViewUpdate) AddLeftWidth(v int) *ViewUpdate {
	_u.mutation.AddLeftWidth(v)
	return _u
}

// SetRightWidth sets the "right_width" field.
func (_u *ViewUpdate) SetRightWidth(v int) *ViewUpdate {
	_u.mutation.ResetRightWidth()
	_u.mutation.SetRightWidth(v)
	return _u
}

// SetNillableRightWidth sets the "right_width" field if the given value is not nil.
func (_u *ViewUpdate) SetNillableRightWidth(v *int) *ViewUpdate {
	if v != nil {
		_u.SetRightWidth(*v)
	}
	return _u
}

// AddRightWidth adds value to the "right_width" field.
func (_u *ViewUpdate) AddRightWidth(v int) *ViewUpdate {
	_u.mutation.AddRightWidth(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ViewUpdate) SetUpdatedAt(v time.Time) *ViewUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ViewMutation object of the builder.
func (_u *ViewUpdate) Mutation() *ViewMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ViewUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ViewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ViewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ViewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ViewUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := view.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ViewUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := view.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "View.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ViewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(view.Table, view.Columns, sqlgraph.NewFieldSpec(view.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(view.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Teams(); ok {
		_spec.SetField(view.FieldTeams, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTeams(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, view.FieldTeams, value)
		})
	}
	if value, ok := _u.mutation.NodePositions(); ok {
		_spec.SetField(view.FieldNodePositions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.LeftWidth(); ok {
		_spec.SetField(view.FieldLeftWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLeftWidth(); ok {
		_spec.AddField(view.FieldLeftWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RightWidth(); ok {
		_spec.SetField(view.FieldRightWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRightWidth(); ok {
		_spec.AddField(view.FieldRightWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(view.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{view.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ViewUpdateOne is the builder for updating a single View entity.
type ViewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ViewMutation
}

// SetName sets the "name" field.
func (_u *ViewUpdateOne) SetName(v string) *ViewUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ViewUpdateOne) SetNillableName(v *string) *ViewUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTeams sets the "teams" field.
func (_u *ViewUpdateOne) SetTeams(v []string) *ViewUpdateOne {
	_u.mutation.SetTeams(v)
	return _u
}

// AppendTeams appends value to the "teams" field.
func (_u *ViewUpdateOne) AppendTeams(v []string) *ViewUpdateOne {
	_u.mutation.AppendTeams(v)
	return _u
}

// SetNodePositions sets the "node_positions" field.
func (_u *ViewUpdateOne) SetNodePositions(v map[string]map[string]schema.Position) *ViewUpdateOne {
	_u.mutation.SetNodePositions(v)
	return _u
}

// SetLeftWidth sets the "left_width" field.
func (_u *ViewUpdateOne) SetLeftWidth(v int) *ViewUpdateOne {
	_u.mutation.ResetLeftWidth()
	_u.mutation.SetLeftWidth(v)
	return _u
}

// SetNillableLeftWidth sets the "left_width" field if the given value is not nil.
func (_u *ViewUpdateOne) SetNillableLeftWidth(v *int) *ViewUpdateOne {
	if v != nil {
		_u.SetLeftWidth(*v)
	}
	return _u
}

// AddLeftWidth adds value to the "left_width" field.
func (_u *ViewUpdateOne) AddLeftWidth(v int) *ViewUpdateOne {
	_u.mutation.AddLeftWidth(v)
	return _u
}

// SetRightWidth sets the "right_width" field.
func (_u *ViewUpdateOne) SetRightWidth(v int) *ViewUpdateOne {
	_u.mutation.ResetRightWidth()
	_u.mutation.SetRightWidth(v)
	return _u
}

// SetNillableRightWidth sets the "right_width" field if the given value is not nil.
func (_u *ViewUpdateOne) SetNillableRightWidth(v *int) *ViewUpdateOne {
	if v != nil {
		_u.SetRightWidth(*v)
	}
	return _u
}

// AddRightWidth adds value to the "right_width" field.
func (_u *ViewUpdateOne) AddRightWidth(v int) *ViewUpdateOne {
	_u.mutation.AddRightWidth(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ViewUpdateOne) SetUpdatedAt(v time.Time) *ViewUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ViewMutation object of the builder.
func (_u *ViewUpdateOne) Mutation() *ViewMutation {
	return _u.mutation
}

// Where appends a list predicates to the ViewUpdate builder.
func (_u *ViewUpdateOne) Where(ps ...predicate.View) *ViewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ViewUpdateOne) Select(field string, fields ...string) *ViewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated View entity.
func (_u *ViewUpdateOne) Save(ctx context.Context) (*View, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ViewUpdateOne) SaveX(ctx context.Context) *View {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ViewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ViewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ViewUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := view.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ViewUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := view.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "View.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ViewUpdateOne) sqlSave(ctx context.Context) (_node *View, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(view.Table, view.Columns, sqlgraph.NewFieldSpec(view.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "View.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, view.FieldID)
		for _, f := range fields {
			if !view.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != view.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(view.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Teams(); ok {
		_spec.SetField(view.FieldTeams, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTeams(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, view.FieldTeams, value)
		})
	}
	if value, ok := _u.mutation.NodePositions(); ok {
		_spec.SetField(view.FieldNodePositions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.LeftWidth(); ok {
		_spec.SetField(view.FieldLeftWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLeftWidth(); ok {
		_spec.AddField(view.FieldLeftWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RightWidth(); ok {
		_spec.SetField(view.FieldRightWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRightWidth(); ok {
		_spec.AddField(view.FieldRightWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(view.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &View{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{view.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
