// Code generated by ent, DO NOT EDIT.

package view

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the view type in the database.
	Label = "view"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTeams holds the string denoting the teams field in the database.
	FieldTeams = "teams"
	// FieldNodePositions holds the string denoting the node_positions field in the database.
	FieldNodePositions = "node_positions"
	// FieldLeftWidth holds the string denoting the left_width field in the database.
	FieldLeftWidth = "left_width"
	// FieldRightWidth holds the string denoting the right_width field in the database.
	FieldRightWidth = "right_width"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the view in the database.
	Table = "views"
)

// Columns holds all SQL columns for view fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTeams,
	FieldNodePositions,
	FieldLeftWidth,
	FieldRightWidth,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultLeftWidth holds the default value on creation for the "left_width" field.
	DefaultLeftWidth int
	// DefaultRightWidth holds the default value on creation for the "right_width" field.
	DefaultRightWidth int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the View queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLeftWidth orders the results by the left_width field.
func ByLeftWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeftWidth, opts...).ToFunc()
}

// ByRightWidth orders the results by the right_width field.
func ByRightWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRightWidth, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
