// Code generated by ent, DO NOT EDIT.

package view

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/agentplexus/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.View {
	return predicate.View(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.View {
	return predicate.View(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.View {
	return predicate.View(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.View {
	return predicate.View(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.View {
	return predicate.View(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.View {
	return predicate.View(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.View {
	return predicate.View(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.View {
	return predicate.View(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.View {
	return predicate.View(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.View {
	return predicate.View(sql.FieldEQ(FieldName, v))
}

// LeftWidth applies equality check predicate on the "left_width" field. It's identical to LeftWidthEQ.
func LeftWidth(v int) predicate.View {
	return predicate.View(sql.FieldEQ(FieldLeftWidth, v))
}

// RightWidth applies equality check predicate on the "right_width" field. It's identical to RightWidthEQ.
func RightWidth(v int) predicate.View {
	return predicate.View(sql.FieldEQ(FieldRightWidth, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.View {
	return predicate.View(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.View {
	return predicate.View(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.View {
	return predicate.View(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.View {
	return predicate.View(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.View {
	return predicate.View(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.View {
	return predicate.View(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.View {
	return predicate.View(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.View {
	return predicate.View(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.View {
	return predicate.View(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.View {
	return predicate.View(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.View {
	return predicate.View(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.View {
	return predicate.View(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.View {
	return predicate.View(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.View {
	return predicate.View(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.View {
	return predicate.View(sql.FieldContainsFold(FieldName, v))
}

// LeftWidthEQ applies the EQ predicate on the "left_width" field.
func LeftWidthEQ(v int) predicate.View {
	return predicate.View(sql.FieldEQ(FieldLeftWidth, v))
}

// LeftWidthNEQ applies the NEQ predicate on the "left_width" field.
func LeftWidthNEQ(v int) predicate.View {
	return predicate.View(sql.FieldNEQ(FieldLeftWidth, v))
}

// LeftWidthIn applies the In predicate on the "left_width" field.
func LeftWidthIn(vs ...int) predicate.View {
	return predicate.View(sql.FieldIn(FieldLeftWidth, vs...))
}

// LeftWidthNotIn applies the NotIn predicate on the "left_width" field.
func LeftWidthNotIn(vs ...int) predicate.View {
	return predicate.View(sql.FieldNotIn(FieldLeftWidth, vs...))
}

// LeftWidthGT applies the GT predicate on the "left_width" field.
func LeftWidthGT(v int) predicate.View {
	return predicate.View(sql.FieldGT(FieldLeftWidth, v))
}

// LeftWidthGTE applies the GTE predicate on the "left_width" field.
func LeftWidthGTE(v int) predicate.View {
	return predicate.View(sql.FieldGTE(FieldLeftWidth, v))
}

// LeftWidthLT applies the LT predicate on the "left_width" field.
func LeftWidthLT(v int) predicate.View {
	return predicate.View(sql.FieldLT(FieldLeftWidth, v))
}

// LeftWidthLTE applies the LTE predicate on the "left_width" field.
func LeftWidthLTE(v int) predicate.View {
	return predicate.View(sql.FieldLTE(FieldLeftWidth, v))
}

// RightWidthEQ applies the EQ predicate on the "right_width" field.
func RightWidthEQ(v int) predicate.View {
	return predicate.View(sql.FieldEQ(FieldRightWidth, v))
}

// RightWidthNEQ applies the NEQ predicate on the "right_width" field.
func RightWidthNEQ(v int) predicate.View {
	return predicate.View(sql.FieldNEQ(FieldRightWidth, v))
}

// RightWidthIn applies the In predicate on the "right_width" field.
func RightWidthIn(vs ...int) predicate.View {
	return predicate.View(sql.FieldIn(FieldRightWidth, vs...))
}

// RightWidthNotIn applies the NotIn predicate on the "right_width" field.
func RightWidthNotIn(vs ...int) predicate.View {
	return predicate.View(sql.FieldNotIn(FieldRightWidth, vs...))
}

// RightWidthGT applies the GT predicate on the "right_width" field.
func RightWidthGT(v int) predicate.View {
	return predicate.View(sql.FieldGT(FieldRightWidth, v))
}

// RightWidthGTE applies the GTE predicate on the "right_width" field.
func RightWidthGTE(v int) predicate.View {
	return predicate.View(sql.FieldGTE(FieldRightWidth, v))
}

// RightWidthLT applies the LT predicate on the "right_width" field.
func RightWidthLT(v int) predicate.View {
	return predicate.View(sql.FieldLT(FieldRightWidth, v))
}

// RightWidthLTE applies the LTE predicate on the "right_width" field.
func RightWidthLTE(v int) predicate.View {
	return predicate.View(sql.FieldLTE(FieldRightWidth, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.View {
	return predicate.View(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.View {
	return predicate.View(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.View {
	return predicate.View(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.View {
	return predicate.View(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.View {
	return predicate.View(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.View {
	return predicate.View(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.View {
	return predicate.View(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.View {
	return predicate.View(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.View {
	return predicate.View(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.View {
	return predicate.View(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.View {
	return predicate.View(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.View {
	return predicate.View(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.View {
	return predicate.View(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.View {
	return predicate.View(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.View {
	return predicate.View(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.View {
	return predicate.View(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.View) predicate.View {
	return predicate.View(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.View) predicate.View {
	return predicate.View(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.View) predicate.View {
	return predicate.View(sql.NotPredicates(p))
}
