// Code generated by ent, DO NOT EDIT.

package agentdefinition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the agentdefinition type in the database.
	Label = "agent_definition"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepoName holds the string denoting the repo_name field in the database.
	FieldRepoName = "repo_name"
	// FieldNamespace holds the string denoting the namespace field in the database.
	FieldNamespace = "namespace"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldQualifiedName holds the string denoting the qualified_name field in the database.
	FieldQualifiedName = "qualified_name"
	// FieldSourceRef holds the string denoting the source_ref field in the database.
	FieldSourceRef = "source_ref"
	// FieldRegistryXrn holds the string denoting the registry_xrn field in the database.
	FieldRegistryXrn = "registry_xrn"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldTools holds the string denoting the tools field in the database.
	FieldTools = "tools"
	// FieldAllowedTools holds the string denoting the allowed_tools field in the database.
	FieldAllowedTools = "allowed_tools"
	// FieldSkills holds the string denoting the skills field in the database.
	FieldSkills = "skills"
	// FieldDependencies holds the string denoting the dependencies field in the database.
	FieldDependencies = "dependencies"
	// FieldRequires holds the string denoting the requires field in the database.
	FieldRequires = "requires"
	// FieldSourcePath holds the string denoting the source_path field in the database.
	FieldSourcePath = "source_path"
	// FieldContentHash holds the string denoting the content_hash field in the database.
	FieldContentHash = "content_hash"
	// FieldFirstSeenAt holds the string denoting the first_seen_at field in the database.
	FieldFirstSeenAt = "first_seen_at"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTeams holds the string denoting the teams edge name in mutations.
	EdgeTeams = "teams"
	// Table holds the table name of the agentdefinition in the database.
	Table = "agent_definitions"
	// TeamsTable is the table that holds the teams relation/edge. The primary key declared below.
	TeamsTable = "team_definition_agents"
	// TeamsInverseTable is the table name for the TeamDefinition entity.
	// It exists in this package in order to avoid circular dependency with the "teamdefinition" package.
	TeamsInverseTable = "team_definitions"
)

// Columns holds all SQL columns for agentdefinition fields.
var Columns = []string{
	FieldID,
	FieldRepoName,
	FieldNamespace,
	FieldName,
	FieldQualifiedName,
	FieldSourceRef,
	FieldRegistryXrn,
	FieldDescription,
	FieldModel,
	FieldIcon,
	FieldRole,
	FieldTools,
	FieldAllowedTools,
	FieldSkills,
	FieldDependencies,
	FieldRequires,
	FieldSourcePath,
	FieldContentHash,
	FieldFirstSeenAt,
	FieldLastSeenAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// TeamsPrimaryKey and TeamsColumn2 are the table columns denoting the
	// primary key for the teams relation (M2M).
	TeamsPrimaryKey = []string{"team_definition_id", "agent_definition_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RepoNameValidator is a validator for the "repo_name" field. It is called by the builders before save.
	RepoNameValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// QualifiedNameValidator is a validator for the "qualified_name" field. It is called by the builders before save.
	QualifiedNameValidator func(string) error
	// SourcePathValidator is a validator for the "source_path" field. It is called by the builders before save.
	SourcePathValidator func(string) error
	// ContentHashValidator is a validator for the "content_hash" field. It is called by the builders before save.
	ContentHashValidator func(string) error
	// DefaultFirstSeenAt holds the default value on creation for the "first_seen_at" field.
	DefaultFirstSeenAt func() time.Time
	// DefaultLastSeenAt holds the default value on creation for the "last_seen_at" field.
	DefaultLastSeenAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the AgentDefinition queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepoName orders the results by the repo_name field.
func ByRepoName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoName, opts...).ToFunc()
}

// ByNamespace orders the results by the namespace field.
func ByNamespace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamespace, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByQualifiedName orders the results by the qualified_name field.
func ByQualifiedName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQualifiedName, opts...).ToFunc()
}

// BySourceRef orders the results by the source_ref field.
func BySourceRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceRef, opts...).ToFunc()
}

// ByRegistryXrn orders the results by the registry_xrn field.
func ByRegistryXrn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegistryXrn, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByIcon orders the results by the icon field.
func ByIcon(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIcon, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// BySourcePath orders the results by the source_path field.
func BySourcePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourcePath, opts...).ToFunc()
}

// ByContentHash orders the results by the content_hash field.
func ByContentHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentHash, opts...).ToFunc()
}

// ByFirstSeenAt orders the results by the first_seen_at field.
func ByFirstSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstSeenAt, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTeamsCount orders the results by teams count.
func ByTeamsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamsStep(), opts...)
	}
}

// ByTeams orders the results by teams terms.
func ByTeams(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTeamsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, TeamsTable, TeamsPrimaryKey...),
	)
}
