// Code generated by ent, DO NOT EDIT.

package agentdefinition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/plexusone/agentplexus/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldID, id))
}

// RepoName applies equality check predicate on the "repo_name" field. It's identical to RepoNameEQ.
func RepoName(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldRepoName, v))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldNamespace, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldName, v))
}

// QualifiedName applies equality check predicate on the "qualified_name" field. It's identical to QualifiedNameEQ.
func QualifiedName(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldQualifiedName, v))
}

// SourceRef applies equality check predicate on the "source_ref" field. It's identical to SourceRefEQ.
func SourceRef(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldSourceRef, v))
}

// RegistryXrn applies equality check predicate on the "registry_xrn" field. It's identical to RegistryXrnEQ.
func RegistryXrn(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldRegistryXrn, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldDescription, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldModel, v))
}

// Icon applies equality check predicate on the "icon" field. It's identical to IconEQ.
func Icon(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldIcon, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldRole, v))
}

// SourcePath applies equality check predicate on the "source_path" field. It's identical to SourcePathEQ.
func SourcePath(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldSourcePath, v))
}

// ContentHash applies equality check predicate on the "content_hash" field. It's identical to ContentHashEQ.
func ContentHash(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldContentHash, v))
}

// FirstSeenAt applies equality check predicate on the "first_seen_at" field. It's identical to FirstSeenAtEQ.
func FirstSeenAt(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldFirstSeenAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// RepoNameEQ applies the EQ predicate on the "repo_name" field.
func RepoNameEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldRepoName, v))
}

// RepoNameNEQ applies the NEQ predicate on the "repo_name" field.
func RepoNameNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldRepoName, v))
}

// RepoNameIn applies the In predicate on the "repo_name" field.
func RepoNameIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldRepoName, vs...))
}

// RepoNameNotIn applies the NotIn predicate on the "repo_name" field.
func RepoNameNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldRepoName, vs...))
}

// RepoNameGT applies the GT predicate on the "repo_name" field.
func RepoNameGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldRepoName, v))
}

// RepoNameGTE applies the GTE predicate on the "repo_name" field.
func RepoNameGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldRepoName, v))
}

// RepoNameLT applies the LT predicate on the "repo_name" field.
func RepoNameLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldRepoName, v))
}

// RepoNameLTE applies the LTE predicate on the "repo_name" field.
func RepoNameLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldRepoName, v))
}

// RepoNameContains applies the Contains predicate on the "repo_name" field.
func RepoNameContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldRepoName, v))
}

// RepoNameHasPrefix applies the HasPrefix predicate on the "repo_name" field.
func RepoNameHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldRepoName, v))
}

// RepoNameHasSuffix applies the HasSuffix predicate on the "repo_name" field.
func RepoNameHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldRepoName, v))
}

// RepoNameEqualFold applies the EqualFold predicate on the "repo_name" field.
func RepoNameEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldRepoName, v))
}

// RepoNameContainsFold applies the ContainsFold predicate on the "repo_name" field.
func RepoNameContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldRepoName, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldNamespace, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldName, v))
}

// QualifiedNameEQ applies the EQ predicate on the "qualified_name" field.
func QualifiedNameEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldQualifiedName, v))
}

// QualifiedNameNEQ applies the NEQ predicate on the "qualified_name" field.
func QualifiedNameNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldQualifiedName, v))
}

// QualifiedNameIn applies the In predicate on the "qualified_name" field.
func QualifiedNameIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldQualifiedName, vs...))
}

// QualifiedNameNotIn applies the NotIn predicate on the "qualified_name" field.
func QualifiedNameNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldQualifiedName, vs...))
}

// QualifiedNameGT applies the GT predicate on the "qualified_name" field.
func QualifiedNameGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldQualifiedName, v))
}

// QualifiedNameGTE applies the GTE predicate on the "qualified_name" field.
func QualifiedNameGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldQualifiedName, v))
}

// QualifiedNameLT applies the LT predicate on the "qualified_name" field.
func QualifiedNameLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldQualifiedName, v))
}

// QualifiedNameLTE applies the LTE predicate on the "qualified_name" field.
func QualifiedNameLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldQualifiedName, v))
}

// QualifiedNameContains applies the Contains predicate on the "qualified_name" field.
func QualifiedNameContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldQualifiedName, v))
}

// QualifiedNameHasPrefix applies the HasPrefix predicate on the "qualified_name" field.
func QualifiedNameHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldQualifiedName, v))
}

// QualifiedNameHasSuffix applies the HasSuffix predicate on the "qualified_name" field.
func QualifiedNameHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldQualifiedName, v))
}

// QualifiedNameEqualFold applies the EqualFold predicate on the "qualified_name" field.
func QualifiedNameEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldQualifiedName, v))
}

// QualifiedNameContainsFold applies the ContainsFold predicate on the "qualified_name" field.
func QualifiedNameContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldQualifiedName, v))
}

// SourceRefEQ applies the EQ predicate on the "source_ref" field.
func SourceRefEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldSourceRef, v))
}

// SourceRefNEQ applies the NEQ predicate on the "source_ref" field.
func SourceRefNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldSourceRef, v))
}

// SourceRefIn applies the In predicate on the "source_ref" field.
func SourceRefIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldSourceRef, vs...))
}

// SourceRefNotIn applies the NotIn predicate on the "source_ref" field.
func SourceRefNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldSourceRef, vs...))
}

// SourceRefGT applies the GT predicate on the "source_ref" field.
func SourceRefGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldSourceRef, v))
}

// SourceRefGTE applies the GTE predicate on the "source_ref" field.
func SourceRefGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldSourceRef, v))
}

// SourceRefLT applies the LT predicate on the "source_ref" field.
func SourceRefLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldSourceRef, v))
}

// SourceRefLTE applies the LTE predicate on the "source_ref" field.
func SourceRefLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldSourceRef, v))
}

// SourceRefContains applies the Contains predicate on the "source_ref" field.
func SourceRefContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldSourceRef, v))
}

// SourceRefHasPrefix applies the HasPrefix predicate on the "source_ref" field.
func SourceRefHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldSourceRef, v))
}

// SourceRefHasSuffix applies the HasSuffix predicate on the "source_ref" field.
func SourceRefHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldSourceRef, v))
}

// SourceRefIsNil applies the IsNil predicate on the "source_ref" field.
func SourceRefIsNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIsNull(FieldSourceRef))
}

// SourceRefNotNil applies the NotNil predicate on the "source_ref" field.
func SourceRefNotNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotNull(FieldSourceRef))
}

// SourceRefEqualFold applies the EqualFold predicate on the "source_ref" field.
func SourceRefEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldSourceRef, v))
}

// SourceRefContainsFold applies the ContainsFold predicate on the "source_ref" field.
func SourceRefContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldSourceRef, v))
}

// RegistryXrnEQ applies the EQ predicate on the "registry_xrn" field.
func RegistryXrnEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldRegistryXrn, v))
}

// RegistryXrnNEQ applies the NEQ predicate on the "registry_xrn" field.
func RegistryXrnNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldRegistryXrn, v))
}

// RegistryXrnIn applies the In predicate on the "registry_xrn" field.
func RegistryXrnIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldRegistryXrn, vs...))
}

// RegistryXrnNotIn applies the NotIn predicate on the "registry_xrn" field.
func RegistryXrnNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldRegistryXrn, vs...))
}

// RegistryXrnGT applies the GT predicate on the "registry_xrn" field.
func RegistryXrnGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldRegistryXrn, v))
}

// RegistryXrnGTE applies the GTE predicate on the "registry_xrn" field.
func RegistryXrnGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldRegistryXrn, v))
}

// RegistryXrnLT applies the LT predicate on the "registry_xrn" field.
func RegistryXrnLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldRegistryXrn, v))
}

// RegistryXrnLTE applies the LTE predicate on the "registry_xrn" field.
func RegistryXrnLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldRegistryXrn, v))
}

// RegistryXrnContains applies the Contains predicate on the "registry_xrn" field.
func RegistryXrnContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldRegistryXrn, v))
}

// RegistryXrnHasPrefix applies the HasPrefix predicate on the "registry_xrn" field.
func RegistryXrnHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldRegistryXrn, v))
}

// RegistryXrnHasSuffix applies the HasSuffix predicate on the "registry_xrn" field.
func RegistryXrnHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldRegistryXrn, v))
}

// RegistryXrnIsNil applies the IsNil predicate on the "registry_xrn" field.
func RegistryXrnIsNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIsNull(FieldRegistryXrn))
}

// RegistryXrnNotNil applies the NotNil predicate on the "registry_xrn" field.
func RegistryXrnNotNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotNull(FieldRegistryXrn))
}

// RegistryXrnEqualFold applies the EqualFold predicate on the "registry_xrn" field.
func RegistryXrnEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldRegistryXrn, v))
}

// RegistryXrnContainsFold applies the ContainsFold predicate on the "registry_xrn" field.
func RegistryXrnContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldRegistryXrn, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldDescription, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldModel, v))
}

// IconEQ applies the EQ predicate on the "icon" field.
func IconEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldIcon, v))
}

// IconNEQ applies the NEQ predicate on the "icon" field.
func IconNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldIcon, v))
}

// IconIn applies the In predicate on the "icon" field.
func IconIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldIcon, vs...))
}

// IconNotIn applies the NotIn predicate on the "icon" field.
func IconNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldIcon, vs...))
}

// IconGT applies the GT predicate on the "icon" field.
func IconGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldIcon, v))
}

// IconGTE applies the GTE predicate on the "icon" field.
func IconGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldIcon, v))
}

// IconLT applies the LT predicate on the "icon" field.
func IconLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldIcon, v))
}

// IconLTE applies the LTE predicate on the "icon" field.
func IconLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldIcon, v))
}

// IconContains applies the Contains predicate on the "icon" field.
func IconContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldIcon, v))
}

// IconHasPrefix applies the HasPrefix predicate on the "icon" field.
func IconHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldIcon, v))
}

// IconHasSuffix applies the HasSuffix predicate on the "icon" field.
func IconHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldIcon, v))
}

// IconIsNil applies the IsNil predicate on the "icon" field.
func IconIsNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIsNull(FieldIcon))
}

// IconNotNil applies the NotNil predicate on the "icon" field.
func IconNotNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotNull(FieldIcon))
}

// IconEqualFold applies the EqualFold predicate on the "icon" field.
func IconEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldIcon, v))
}

// IconContainsFold applies the ContainsFold predicate on the "icon" field.
func IconContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldIcon, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldRole, v))
}

// RoleIsNil applies the IsNil predicate on the "role" field.
func RoleIsNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIsNull(FieldRole))
}

// RoleNotNil applies the NotNil predicate on the "role" field.
func RoleNotNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotNull(FieldRole))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldRole, v))
}

// ToolsIsNil applies the IsNil predicate on the "tools" field.
func ToolsIsNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIsNull(FieldTools))
}

// ToolsNotNil applies the NotNil predicate on the "tools" field.
func ToolsNotNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotNull(FieldTools))
}

// AllowedToolsIsNil applies the IsNil predicate on the "allowed_tools" field.
func AllowedToolsIsNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIsNull(FieldAllowedTools))
}

// AllowedToolsNotNil applies the NotNil predicate on the "allowed_tools" field.
func AllowedToolsNotNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotNull(FieldAllowedTools))
}

// SkillsIsNil applies the IsNil predicate on the "skills" field.
func SkillsIsNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIsNull(FieldSkills))
}

// SkillsNotNil applies the NotNil predicate on the "skills" field.
func SkillsNotNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotNull(FieldSkills))
}

// DependenciesIsNil applies the IsNil predicate on the "dependencies" field.
func DependenciesIsNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIsNull(FieldDependencies))
}

// DependenciesNotNil applies the NotNil predicate on the "dependencies" field.
func DependenciesNotNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotNull(FieldDependencies))
}

// RequiresIsNil applies the IsNil predicate on the "requires" field.
func RequiresIsNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIsNull(FieldRequires))
}

// RequiresNotNil applies the NotNil predicate on the "requires" field.
func RequiresNotNil() predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotNull(FieldRequires))
}

// SourcePathEQ applies the EQ predicate on the "source_path" field.
func SourcePathEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldSourcePath, v))
}

// SourcePathNEQ applies the NEQ predicate on the "source_path" field.
func SourcePathNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldSourcePath, v))
}

// SourcePathIn applies the In predicate on the "source_path" field.
func SourcePathIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldSourcePath, vs...))
}

// SourcePathNotIn applies the NotIn predicate on the "source_path" field.
func SourcePathNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldSourcePath, vs...))
}

// SourcePathGT applies the GT predicate on the "source_path" field.
func SourcePathGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldSourcePath, v))
}

// SourcePathGTE applies the GTE predicate on the "source_path" field.
func SourcePathGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldSourcePath, v))
}

// SourcePathLT applies the LT predicate on the "source_path" field.
func SourcePathLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldSourcePath, v))
}

// SourcePathLTE applies the LTE predicate on the "source_path" field.
func SourcePathLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldSourcePath, v))
}

// SourcePathContains applies the Contains predicate on the "source_path" field.
func SourcePathContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldSourcePath, v))
}

// SourcePathHasPrefix applies the HasPrefix predicate on the "source_path" field.
func SourcePathHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldSourcePath, v))
}

// SourcePathHasSuffix applies the HasSuffix predicate on the "source_path" field.
func SourcePathHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldSourcePath, v))
}

// SourcePathEqualFold applies the EqualFold predicate on the "source_path" field.
func SourcePathEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldSourcePath, v))
}

// SourcePathContainsFold applies the ContainsFold predicate on the "source_path" field.
func SourcePathContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldSourcePath, v))
}

// ContentHashEQ applies the EQ predicate on the "content_hash" field.
func ContentHashEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldContentHash, v))
}

// ContentHashNEQ applies the NEQ predicate on the "content_hash" field.
func ContentHashNEQ(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldContentHash, v))
}

// ContentHashIn applies the In predicate on the "content_hash" field.
func ContentHashIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldContentHash, vs...))
}

// ContentHashNotIn applies the NotIn predicate on the "content_hash" field.
func ContentHashNotIn(vs ...string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldContentHash, vs...))
}

// ContentHashGT applies the GT predicate on the "content_hash" field.
func ContentHashGT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldContentHash, v))
}

// ContentHashGTE applies the GTE predicate on the "content_hash" field.
func ContentHashGTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldContentHash, v))
}

// ContentHashLT applies the LT predicate on the "content_hash" field.
func ContentHashLT(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldContentHash, v))
}

// ContentHashLTE applies the LTE predicate on the "content_hash" field.
func ContentHashLTE(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldContentHash, v))
}

// ContentHashContains applies the Contains predicate on the "content_hash" field.
func ContentHashContains(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContains(FieldContentHash, v))
}

// ContentHashHasPrefix applies the HasPrefix predicate on the "content_hash" field.
func ContentHashHasPrefix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasPrefix(FieldContentHash, v))
}

// ContentHashHasSuffix applies the HasSuffix predicate on the "content_hash" field.
func ContentHashHasSuffix(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldHasSuffix(FieldContentHash, v))
}

// ContentHashEqualFold applies the EqualFold predicate on the "content_hash" field.
func ContentHashEqualFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEqualFold(FieldContentHash, v))
}

// ContentHashContainsFold applies the ContainsFold predicate on the "content_hash" field.
func ContentHashContainsFold(v string) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldContainsFold(FieldContentHash, v))
}

// FirstSeenAtEQ applies the EQ predicate on the "first_seen_at" field.
func FirstSeenAtEQ(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtNEQ applies the NEQ predicate on the "first_seen_at" field.
func FirstSeenAtNEQ(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtIn applies the In predicate on the "first_seen_at" field.
func FirstSeenAtIn(vs ...time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtNotIn applies the NotIn predicate on the "first_seen_at" field.
func FirstSeenAtNotIn(vs ...time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtGT applies the GT predicate on the "first_seen_at" field.
func FirstSeenAtGT(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldFirstSeenAt, v))
}

// FirstSeenAtGTE applies the GTE predicate on the "first_seen_at" field.
func FirstSeenAtGTE(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldFirstSeenAt, v))
}

// FirstSeenAtLT applies the LT predicate on the "first_seen_at" field.
func FirstSeenAtLT(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldFirstSeenAt, v))
}

// FirstSeenAtLTE applies the LTE predicate on the "first_seen_at" field.
func FirstSeenAtLTE(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldFirstSeenAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldLastSeenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTeams applies the HasEdge predicate on the "teams" edge.
func HasTeams() predicate.AgentDefinition {
	return predicate.AgentDefinition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, TeamsTable, TeamsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamsWith applies the HasEdge predicate on the "teams" edge with a given conditions (other predicates).
func HasTeamsWith(preds ...predicate.TeamDefinition) predicate.AgentDefinition {
	return predicate.AgentDefinition(func(s *sql.Selector) {
		step := newTeamsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentDefinition) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentDefinition) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentDefinition) predicate.AgentDefinition {
	return predicate.AgentDefinition(sql.NotPredicates(p))
}
